// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: conversations.proto

package com.textrcs.gmproto.conversations;

/**
 * Protobuf type {@code conversations.ContactNumber}
 */
public final class ContactNumber extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:conversations.ContactNumber)
    ContactNumberOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ContactNumber.newBuilder() to construct.
  private ContactNumber(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ContactNumber() {
    number_ = "";
    number2_ = "";
    formattedNumber_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ContactNumber();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.textrcs.gmproto.conversations.Conversations.internal_static_conversations_ContactNumber_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.textrcs.gmproto.conversations.Conversations.internal_static_conversations_ContactNumber_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.textrcs.gmproto.conversations.ContactNumber.class, com.textrcs.gmproto.conversations.ContactNumber.Builder.class);
  }

  private int bitField0_;
  public static final int MYSTERIOUSINT_FIELD_NUMBER = 1;
  private int mysteriousInt_ = 0;
  /**
   * <pre>
   * Might be 2 for contact and 7 for user input?
   * </pre>
   *
   * <code>int32 mysteriousInt = 1;</code>
   * @return The mysteriousInt.
   */
  @java.lang.Override
  public int getMysteriousInt() {
    return mysteriousInt_;
  }

  public static final int NUMBER_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object number_ = "";
  /**
   * <code>string number = 2;</code>
   * @return The number.
   */
  @java.lang.Override
  public java.lang.String getNumber() {
    java.lang.Object ref = number_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      number_ = s;
      return s;
    }
  }
  /**
   * <code>string number = 2;</code>
   * @return The bytes for number.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNumberBytes() {
    java.lang.Object ref = number_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      number_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NUMBER2_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object number2_ = "";
  /**
   * <code>string number2 = 3;</code>
   * @return The number2.
   */
  @java.lang.Override
  public java.lang.String getNumber2() {
    java.lang.Object ref = number2_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      number2_ = s;
      return s;
    }
  }
  /**
   * <code>string number2 = 3;</code>
   * @return The bytes for number2.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNumber2Bytes() {
    java.lang.Object ref = number2_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      number2_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FORMATTEDNUMBER_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object formattedNumber_ = "";
  /**
   * <code>optional string formattedNumber = 4;</code>
   * @return Whether the formattedNumber field is set.
   */
  @java.lang.Override
  public boolean hasFormattedNumber() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string formattedNumber = 4;</code>
   * @return The formattedNumber.
   */
  @java.lang.Override
  public java.lang.String getFormattedNumber() {
    java.lang.Object ref = formattedNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      formattedNumber_ = s;
      return s;
    }
  }
  /**
   * <code>optional string formattedNumber = 4;</code>
   * @return The bytes for formattedNumber.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFormattedNumberBytes() {
    java.lang.Object ref = formattedNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      formattedNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (mysteriousInt_ != 0) {
      output.writeInt32(1, mysteriousInt_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(number_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, number_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(number2_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, number2_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, formattedNumber_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (mysteriousInt_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, mysteriousInt_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(number_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, number_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(number2_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, number2_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, formattedNumber_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.textrcs.gmproto.conversations.ContactNumber)) {
      return super.equals(obj);
    }
    com.textrcs.gmproto.conversations.ContactNumber other = (com.textrcs.gmproto.conversations.ContactNumber) obj;

    if (getMysteriousInt()
        != other.getMysteriousInt()) return false;
    if (!getNumber()
        .equals(other.getNumber())) return false;
    if (!getNumber2()
        .equals(other.getNumber2())) return false;
    if (hasFormattedNumber() != other.hasFormattedNumber()) return false;
    if (hasFormattedNumber()) {
      if (!getFormattedNumber()
          .equals(other.getFormattedNumber())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MYSTERIOUSINT_FIELD_NUMBER;
    hash = (53 * hash) + getMysteriousInt();
    hash = (37 * hash) + NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getNumber().hashCode();
    hash = (37 * hash) + NUMBER2_FIELD_NUMBER;
    hash = (53 * hash) + getNumber2().hashCode();
    if (hasFormattedNumber()) {
      hash = (37 * hash) + FORMATTEDNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getFormattedNumber().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.textrcs.gmproto.conversations.ContactNumber parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.conversations.ContactNumber parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.conversations.ContactNumber parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.conversations.ContactNumber parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.conversations.ContactNumber parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.conversations.ContactNumber parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.conversations.ContactNumber parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.conversations.ContactNumber parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.textrcs.gmproto.conversations.ContactNumber parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.conversations.ContactNumber parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.textrcs.gmproto.conversations.ContactNumber parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.conversations.ContactNumber parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.textrcs.gmproto.conversations.ContactNumber prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code conversations.ContactNumber}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:conversations.ContactNumber)
      com.textrcs.gmproto.conversations.ContactNumberOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.textrcs.gmproto.conversations.Conversations.internal_static_conversations_ContactNumber_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.textrcs.gmproto.conversations.Conversations.internal_static_conversations_ContactNumber_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.textrcs.gmproto.conversations.ContactNumber.class, com.textrcs.gmproto.conversations.ContactNumber.Builder.class);
    }

    // Construct using com.textrcs.gmproto.conversations.ContactNumber.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      mysteriousInt_ = 0;
      number_ = "";
      number2_ = "";
      formattedNumber_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.textrcs.gmproto.conversations.Conversations.internal_static_conversations_ContactNumber_descriptor;
    }

    @java.lang.Override
    public com.textrcs.gmproto.conversations.ContactNumber getDefaultInstanceForType() {
      return com.textrcs.gmproto.conversations.ContactNumber.getDefaultInstance();
    }

    @java.lang.Override
    public com.textrcs.gmproto.conversations.ContactNumber build() {
      com.textrcs.gmproto.conversations.ContactNumber result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.textrcs.gmproto.conversations.ContactNumber buildPartial() {
      com.textrcs.gmproto.conversations.ContactNumber result = new com.textrcs.gmproto.conversations.ContactNumber(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.textrcs.gmproto.conversations.ContactNumber result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.mysteriousInt_ = mysteriousInt_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.number_ = number_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.number2_ = number2_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.formattedNumber_ = formattedNumber_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.textrcs.gmproto.conversations.ContactNumber) {
        return mergeFrom((com.textrcs.gmproto.conversations.ContactNumber)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.textrcs.gmproto.conversations.ContactNumber other) {
      if (other == com.textrcs.gmproto.conversations.ContactNumber.getDefaultInstance()) return this;
      if (other.getMysteriousInt() != 0) {
        setMysteriousInt(other.getMysteriousInt());
      }
      if (!other.getNumber().isEmpty()) {
        number_ = other.number_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getNumber2().isEmpty()) {
        number2_ = other.number2_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasFormattedNumber()) {
        formattedNumber_ = other.formattedNumber_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              mysteriousInt_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              number_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              number2_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              formattedNumber_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int mysteriousInt_ ;
    /**
     * <pre>
     * Might be 2 for contact and 7 for user input?
     * </pre>
     *
     * <code>int32 mysteriousInt = 1;</code>
     * @return The mysteriousInt.
     */
    @java.lang.Override
    public int getMysteriousInt() {
      return mysteriousInt_;
    }
    /**
     * <pre>
     * Might be 2 for contact and 7 for user input?
     * </pre>
     *
     * <code>int32 mysteriousInt = 1;</code>
     * @param value The mysteriousInt to set.
     * @return This builder for chaining.
     */
    public Builder setMysteriousInt(int value) {
      
      mysteriousInt_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Might be 2 for contact and 7 for user input?
     * </pre>
     *
     * <code>int32 mysteriousInt = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMysteriousInt() {
      bitField0_ = (bitField0_ & ~0x00000001);
      mysteriousInt_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object number_ = "";
    /**
     * <code>string number = 2;</code>
     * @return The number.
     */
    public java.lang.String getNumber() {
      java.lang.Object ref = number_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        number_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string number = 2;</code>
     * @return The bytes for number.
     */
    public com.google.protobuf.ByteString
        getNumberBytes() {
      java.lang.Object ref = number_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        number_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string number = 2;</code>
     * @param value The number to set.
     * @return This builder for chaining.
     */
    public Builder setNumber(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      number_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string number = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumber() {
      number_ = getDefaultInstance().getNumber();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string number = 2;</code>
     * @param value The bytes for number to set.
     * @return This builder for chaining.
     */
    public Builder setNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      number_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object number2_ = "";
    /**
     * <code>string number2 = 3;</code>
     * @return The number2.
     */
    public java.lang.String getNumber2() {
      java.lang.Object ref = number2_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        number2_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string number2 = 3;</code>
     * @return The bytes for number2.
     */
    public com.google.protobuf.ByteString
        getNumber2Bytes() {
      java.lang.Object ref = number2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        number2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string number2 = 3;</code>
     * @param value The number2 to set.
     * @return This builder for chaining.
     */
    public Builder setNumber2(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      number2_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string number2 = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumber2() {
      number2_ = getDefaultInstance().getNumber2();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string number2 = 3;</code>
     * @param value The bytes for number2 to set.
     * @return This builder for chaining.
     */
    public Builder setNumber2Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      number2_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object formattedNumber_ = "";
    /**
     * <code>optional string formattedNumber = 4;</code>
     * @return Whether the formattedNumber field is set.
     */
    public boolean hasFormattedNumber() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string formattedNumber = 4;</code>
     * @return The formattedNumber.
     */
    public java.lang.String getFormattedNumber() {
      java.lang.Object ref = formattedNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        formattedNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string formattedNumber = 4;</code>
     * @return The bytes for formattedNumber.
     */
    public com.google.protobuf.ByteString
        getFormattedNumberBytes() {
      java.lang.Object ref = formattedNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        formattedNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string formattedNumber = 4;</code>
     * @param value The formattedNumber to set.
     * @return This builder for chaining.
     */
    public Builder setFormattedNumber(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      formattedNumber_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional string formattedNumber = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFormattedNumber() {
      formattedNumber_ = getDefaultInstance().getFormattedNumber();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>optional string formattedNumber = 4;</code>
     * @param value The bytes for formattedNumber to set.
     * @return This builder for chaining.
     */
    public Builder setFormattedNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      formattedNumber_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:conversations.ContactNumber)
  }

  // @@protoc_insertion_point(class_scope:conversations.ContactNumber)
  private static final com.textrcs.gmproto.conversations.ContactNumber DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.textrcs.gmproto.conversations.ContactNumber();
  }

  public static com.textrcs.gmproto.conversations.ContactNumber getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ContactNumber>
      PARSER = new com.google.protobuf.AbstractParser<ContactNumber>() {
    @java.lang.Override
    public ContactNumber parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ContactNumber> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ContactNumber> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.textrcs.gmproto.conversations.ContactNumber getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

