// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: conversations.proto

package com.textrcs.gmproto.conversations;

public interface ContactNumberOrBuilder extends
    // @@protoc_insertion_point(interface_extends:conversations.ContactNumber)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Might be 2 for contact and 7 for user input?
   * </pre>
   *
   * <code>int32 mysteriousInt = 1;</code>
   * @return The mysteriousInt.
   */
  int getMysteriousInt();

  /**
   * <code>string number = 2;</code>
   * @return The number.
   */
  java.lang.String getNumber();
  /**
   * <code>string number = 2;</code>
   * @return The bytes for number.
   */
  com.google.protobuf.ByteString
      getNumberBytes();

  /**
   * <code>string number2 = 3;</code>
   * @return The number2.
   */
  java.lang.String getNumber2();
  /**
   * <code>string number2 = 3;</code>
   * @return The bytes for number2.
   */
  com.google.protobuf.ByteString
      getNumber2Bytes();

  /**
   * <code>optional string formattedNumber = 4;</code>
   * @return Whether the formattedNumber field is set.
   */
  boolean hasFormattedNumber();
  /**
   * <code>optional string formattedNumber = 4;</code>
   * @return The formattedNumber.
   */
  java.lang.String getFormattedNumber();
  /**
   * <code>optional string formattedNumber = 4;</code>
   * @return The bytes for formattedNumber.
   */
  com.google.protobuf.ByteString
      getFormattedNumberBytes();
}
