// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: conversations.proto

package com.textrcs.gmproto.conversations;

public interface ConversationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:conversations.Conversation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string conversationID = 1;</code>
   * @return The conversationID.
   */
  java.lang.String getConversationID();
  /**
   * <code>string conversationID = 1;</code>
   * @return The bytes for conversationID.
   */
  com.google.protobuf.ByteString
      getConversationIDBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.conversations.LatestMessage latestMessage = 4;</code>
   * @return Whether the latestMessage field is set.
   */
  boolean hasLatestMessage();
  /**
   * <code>.conversations.LatestMessage latestMessage = 4;</code>
   * @return The latestMessage.
   */
  com.textrcs.gmproto.conversations.LatestMessage getLatestMessage();
  /**
   * <code>.conversations.LatestMessage latestMessage = 4;</code>
   */
  com.textrcs.gmproto.conversations.LatestMessageOrBuilder getLatestMessageOrBuilder();

  /**
   * <code>int64 lastMessageTimestamp = 5;</code>
   * @return The lastMessageTimestamp.
   */
  long getLastMessageTimestamp();

  /**
   * <code>bool unread = 6;</code>
   * @return The unread.
   */
  boolean getUnread();

  /**
   * <pre>
   * not certain
   * </pre>
   *
   * <code>bool isGroupChat = 10;</code>
   * @return The isGroupChat.
   */
  boolean getIsGroupChat();

  /**
   * <code>string defaultOutgoingID = 11;</code>
   * @return The defaultOutgoingID.
   */
  java.lang.String getDefaultOutgoingID();
  /**
   * <code>string defaultOutgoingID = 11;</code>
   * @return The bytes for defaultOutgoingID.
   */
  com.google.protobuf.ByteString
      getDefaultOutgoingIDBytes();

  /**
   * <code>.conversations.ConversationStatus status = 12;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.conversations.ConversationStatus status = 12;</code>
   * @return The status.
   */
  com.textrcs.gmproto.conversations.ConversationStatus getStatus();

  /**
   * <code>bool readOnly = 13;</code>
   * @return The readOnly.
   */
  boolean getReadOnly();

  /**
   * <code>string avatarHexColor = 15;</code>
   * @return The avatarHexColor.
   */
  java.lang.String getAvatarHexColor();
  /**
   * <code>string avatarHexColor = 15;</code>
   * @return The bytes for avatarHexColor.
   */
  com.google.protobuf.ByteString
      getAvatarHexColorBytes();

  /**
   * <code>string latestMessageID = 17;</code>
   * @return The latestMessageID.
   */
  java.lang.String getLatestMessageID();
  /**
   * <code>string latestMessageID = 17;</code>
   * @return The bytes for latestMessageID.
   */
  com.google.protobuf.ByteString
      getLatestMessageIDBytes();

  /**
   * <code>.conversations.ConversationSendMode sendMode = 18;</code>
   * @return The enum numeric value on the wire for sendMode.
   */
  int getSendModeValue();
  /**
   * <code>.conversations.ConversationSendMode sendMode = 18;</code>
   * @return The sendMode.
   */
  com.textrcs.gmproto.conversations.ConversationSendMode getSendMode();

  /**
   * <code>repeated .conversations.Participant participants = 20;</code>
   */
  java.util.List<com.textrcs.gmproto.conversations.Participant> 
      getParticipantsList();
  /**
   * <code>repeated .conversations.Participant participants = 20;</code>
   */
  com.textrcs.gmproto.conversations.Participant getParticipants(int index);
  /**
   * <code>repeated .conversations.Participant participants = 20;</code>
   */
  int getParticipantsCount();
  /**
   * <code>repeated .conversations.Participant participants = 20;</code>
   */
  java.util.List<? extends com.textrcs.gmproto.conversations.ParticipantOrBuilder> 
      getParticipantsOrBuilderList();
  /**
   * <code>repeated .conversations.Participant participants = 20;</code>
   */
  com.textrcs.gmproto.conversations.ParticipantOrBuilder getParticipantsOrBuilder(
      int index);

  /**
   * <pre>
   * participant ids excluding me
   * </pre>
   *
   * <code>repeated string otherParticipants = 21;</code>
   * @return A list containing the otherParticipants.
   */
  java.util.List<java.lang.String>
      getOtherParticipantsList();
  /**
   * <pre>
   * participant ids excluding me
   * </pre>
   *
   * <code>repeated string otherParticipants = 21;</code>
   * @return The count of otherParticipants.
   */
  int getOtherParticipantsCount();
  /**
   * <pre>
   * participant ids excluding me
   * </pre>
   *
   * <code>repeated string otherParticipants = 21;</code>
   * @param index The index of the element to return.
   * @return The otherParticipants at the given index.
   */
  java.lang.String getOtherParticipants(int index);
  /**
   * <pre>
   * participant ids excluding me
   * </pre>
   *
   * <code>repeated string otherParticipants = 21;</code>
   * @param index The index of the value to return.
   * @return The bytes of the otherParticipants at the given index.
   */
  com.google.protobuf.ByteString
      getOtherParticipantsBytes(int index);

  /**
   * <code>.conversations.ConversationType type = 22;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.conversations.ConversationType type = 22;</code>
   * @return The type.
   */
  com.textrcs.gmproto.conversations.ConversationType getType();

  /**
   * <code>bool subType = 24;</code>
   * @return The subType.
   */
  boolean getSubType();

  /**
   * <code>bool pinned = 26;</code>
   * @return The pinned.
   */
  boolean getPinned();

  /**
   * <pre>
   * set to lastMessageTimestamp + 1000 when marking as unread?
   * </pre>
   *
   * <code>int64 unknownTimestamp = 28;</code>
   * @return The unknownTimestamp.
   */
  long getUnknownTimestamp();

  /**
   * <code>bool thirdType = 29;</code>
   * @return The thirdType.
   */
  boolean getThirdType();

  /**
   * <code>.conversations.SomeKindOfGroupID someKindOfGroupID = 31;</code>
   * @return Whether the someKindOfGroupID field is set.
   */
  boolean hasSomeKindOfGroupID();
  /**
   * <code>.conversations.SomeKindOfGroupID someKindOfGroupID = 31;</code>
   * @return The someKindOfGroupID.
   */
  com.textrcs.gmproto.conversations.SomeKindOfGroupID getSomeKindOfGroupID();
  /**
   * <code>.conversations.SomeKindOfGroupID someKindOfGroupID = 31;</code>
   */
  com.textrcs.gmproto.conversations.SomeKindOfGroupIDOrBuilder getSomeKindOfGroupIDOrBuilder();

  /**
   * <code>.settings.SIMCard simCard = 32;</code>
   * @return Whether the simCard field is set.
   */
  boolean hasSimCard();
  /**
   * <code>.settings.SIMCard simCard = 32;</code>
   * @return The simCard.
   */
  com.textrcs.gmproto.settings.SIMCard getSimCard();
  /**
   * <code>.settings.SIMCard simCard = 32;</code>
   */
  com.textrcs.gmproto.settings.SIMCardOrBuilder getSimCardOrBuilder();

  /**
   * <pre>
   * URL for group conversation icon (observed on RCS group chats).
   * </pre>
   *
   * <code>string groupAvatarURL = 34;</code>
   * @return The groupAvatarURL.
   */
  java.lang.String getGroupAvatarURL();
  /**
   * <pre>
   * URL for group conversation icon (observed on RCS group chats).
   * </pre>
   *
   * <code>string groupAvatarURL = 34;</code>
   * @return The bytes for groupAvatarURL.
   */
  com.google.protobuf.ByteString
      getGroupAvatarURLBytes();

  /**
   * <code>.conversations.AnotherMessageID latestMessageAnoherID = 35;</code>
   * @return Whether the latestMessageAnoherID field is set.
   */
  boolean hasLatestMessageAnoherID();
  /**
   * <code>.conversations.AnotherMessageID latestMessageAnoherID = 35;</code>
   * @return The latestMessageAnoherID.
   */
  com.textrcs.gmproto.conversations.AnotherMessageID getLatestMessageAnoherID();
  /**
   * <code>.conversations.AnotherMessageID latestMessageAnoherID = 35;</code>
   */
  com.textrcs.gmproto.conversations.AnotherMessageIDOrBuilder getLatestMessageAnoherIDOrBuilder();
}
