// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: conversations.proto

package com.textrcs.gmproto.conversations;

/**
 * Protobuf enum {@code conversations.ConversationStatus}
 */
public enum ConversationStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN_CONVERSATION_STATUS = 0;</code>
   */
  UNKNOWN_CONVERSATION_STATUS(0),
  /**
   * <code>ACTIVE = 1;</code>
   */
  ACTIVE(1),
  /**
   * <code>ARCHIVED = 2;</code>
   */
  ARCHIVED(2),
  /**
   * <code>DELETED = 3;</code>
   */
  DELETED(3),
  /**
   * <code>KEEP_ARCHIVED = 4;</code>
   */
  KEEP_ARCHIVED(4),
  /**
   * <code>SPAM_FOLDER = 5;</code>
   */
  SPAM_FOLDER(5),
  /**
   * <code>BLOCKED_FOLDER = 6;</code>
   */
  BLOCKED_FOLDER(6),
  /**
   * <code>CROSS_COUNTRY_FOLDER = 7;</code>
   */
  CROSS_COUNTRY_FOLDER(7),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOWN_CONVERSATION_STATUS = 0;</code>
   */
  public static final int UNKNOWN_CONVERSATION_STATUS_VALUE = 0;
  /**
   * <code>ACTIVE = 1;</code>
   */
  public static final int ACTIVE_VALUE = 1;
  /**
   * <code>ARCHIVED = 2;</code>
   */
  public static final int ARCHIVED_VALUE = 2;
  /**
   * <code>DELETED = 3;</code>
   */
  public static final int DELETED_VALUE = 3;
  /**
   * <code>KEEP_ARCHIVED = 4;</code>
   */
  public static final int KEEP_ARCHIVED_VALUE = 4;
  /**
   * <code>SPAM_FOLDER = 5;</code>
   */
  public static final int SPAM_FOLDER_VALUE = 5;
  /**
   * <code>BLOCKED_FOLDER = 6;</code>
   */
  public static final int BLOCKED_FOLDER_VALUE = 6;
  /**
   * <code>CROSS_COUNTRY_FOLDER = 7;</code>
   */
  public static final int CROSS_COUNTRY_FOLDER_VALUE = 7;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ConversationStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ConversationStatus forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN_CONVERSATION_STATUS;
      case 1: return ACTIVE;
      case 2: return ARCHIVED;
      case 3: return DELETED;
      case 4: return KEEP_ARCHIVED;
      case 5: return SPAM_FOLDER;
      case 6: return BLOCKED_FOLDER;
      case 7: return CROSS_COUNTRY_FOLDER;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ConversationStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ConversationStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ConversationStatus>() {
          public ConversationStatus findValueByNumber(int number) {
            return ConversationStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.textrcs.gmproto.conversations.Conversations.getDescriptor().getEnumTypes().get(5);
  }

  private static final ConversationStatus[] VALUES = values();

  public static ConversationStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ConversationStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:conversations.ConversationStatus)
}

