// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: conversations.proto

package com.textrcs.gmproto.conversations;

public interface MessageInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:conversations.MessageInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string actionMessageID = 1;</code>
   * @return Whether the actionMessageID field is set.
   */
  boolean hasActionMessageID();
  /**
   * <code>optional string actionMessageID = 1;</code>
   * @return The actionMessageID.
   */
  java.lang.String getActionMessageID();
  /**
   * <code>optional string actionMessageID = 1;</code>
   * @return The bytes for actionMessageID.
   */
  com.google.protobuf.ByteString
      getActionMessageIDBytes();

  /**
   * <code>.conversations.MessageContent messageContent = 2;</code>
   * @return Whether the messageContent field is set.
   */
  boolean hasMessageContent();
  /**
   * <code>.conversations.MessageContent messageContent = 2;</code>
   * @return The messageContent.
   */
  com.textrcs.gmproto.conversations.MessageContent getMessageContent();
  /**
   * <code>.conversations.MessageContent messageContent = 2;</code>
   */
  com.textrcs.gmproto.conversations.MessageContentOrBuilder getMessageContentOrBuilder();

  /**
   * <code>.conversations.MediaContent mediaContent = 3;</code>
   * @return Whether the mediaContent field is set.
   */
  boolean hasMediaContent();
  /**
   * <code>.conversations.MediaContent mediaContent = 3;</code>
   * @return The mediaContent.
   */
  com.textrcs.gmproto.conversations.MediaContent getMediaContent();
  /**
   * <code>.conversations.MediaContent mediaContent = 3;</code>
   */
  com.textrcs.gmproto.conversations.MediaContentOrBuilder getMediaContentOrBuilder();

  public com.textrcs.gmproto.conversations.MessageInfo.DataCase getDataCase();
}
