// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: conversations.proto

package com.textrcs.gmproto.conversations;

/**
 * Protobuf type {@code conversations.MessageStatus}
 */
public final class MessageStatus extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:conversations.MessageStatus)
    MessageStatusOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MessageStatus.newBuilder() to construct.
  private MessageStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MessageStatus() {
    status_ = 0;
    errMsg_ = "";
    statusText_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MessageStatus();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.textrcs.gmproto.conversations.Conversations.internal_static_conversations_MessageStatus_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.textrcs.gmproto.conversations.Conversations.internal_static_conversations_MessageStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.textrcs.gmproto.conversations.MessageStatus.class, com.textrcs.gmproto.conversations.MessageStatus.Builder.class);
  }

  public static final int STATUS_FIELD_NUMBER = 2;
  private int status_ = 0;
  /**
   * <code>.conversations.MessageStatusType status = 2;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.conversations.MessageStatusType status = 2;</code>
   * @return The status.
   */
  @java.lang.Override public com.textrcs.gmproto.conversations.MessageStatusType getStatus() {
    com.textrcs.gmproto.conversations.MessageStatusType result = com.textrcs.gmproto.conversations.MessageStatusType.forNumber(status_);
    return result == null ? com.textrcs.gmproto.conversations.MessageStatusType.UNRECOGNIZED : result;
  }

  public static final int SUBCODE_FIELD_NUMBER = 3;
  private long subCode_ = 0L;
  /**
   * <code>int64 subCode = 3;</code>
   * @return The subCode.
   */
  @java.lang.Override
  public long getSubCode() {
    return subCode_;
  }

  public static final int ERRMSG_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object errMsg_ = "";
  /**
   * <code>string errMsg = 4;</code>
   * @return The errMsg.
   */
  @java.lang.Override
  public java.lang.String getErrMsg() {
    java.lang.Object ref = errMsg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errMsg_ = s;
      return s;
    }
  }
  /**
   * <code>string errMsg = 4;</code>
   * @return The bytes for errMsg.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrMsgBytes() {
    java.lang.Object ref = errMsg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errMsg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUSTEXT_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object statusText_ = "";
  /**
   * <code>string statusText = 5;</code>
   * @return The statusText.
   */
  @java.lang.Override
  public java.lang.String getStatusText() {
    java.lang.Object ref = statusText_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      statusText_ = s;
      return s;
    }
  }
  /**
   * <code>string statusText = 5;</code>
   * @return The bytes for statusText.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusTextBytes() {
    java.lang.Object ref = statusText_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      statusText_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int THIRDCODE_FIELD_NUMBER = 6;
  private long thirdCode_ = 0L;
  /**
   * <code>int64 thirdCode = 6;</code>
   * @return The thirdCode.
   */
  @java.lang.Override
  public long getThirdCode() {
    return thirdCode_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != com.textrcs.gmproto.conversations.MessageStatusType.STATUS_UNKNOWN.getNumber()) {
      output.writeEnum(2, status_);
    }
    if (subCode_ != 0L) {
      output.writeInt64(3, subCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errMsg_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, errMsg_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(statusText_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, statusText_);
    }
    if (thirdCode_ != 0L) {
      output.writeInt64(6, thirdCode_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != com.textrcs.gmproto.conversations.MessageStatusType.STATUS_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, status_);
    }
    if (subCode_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, subCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errMsg_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, errMsg_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(statusText_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, statusText_);
    }
    if (thirdCode_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, thirdCode_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.textrcs.gmproto.conversations.MessageStatus)) {
      return super.equals(obj);
    }
    com.textrcs.gmproto.conversations.MessageStatus other = (com.textrcs.gmproto.conversations.MessageStatus) obj;

    if (status_ != other.status_) return false;
    if (getSubCode()
        != other.getSubCode()) return false;
    if (!getErrMsg()
        .equals(other.getErrMsg())) return false;
    if (!getStatusText()
        .equals(other.getStatusText())) return false;
    if (getThirdCode()
        != other.getThirdCode()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + SUBCODE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSubCode());
    hash = (37 * hash) + ERRMSG_FIELD_NUMBER;
    hash = (53 * hash) + getErrMsg().hashCode();
    hash = (37 * hash) + STATUSTEXT_FIELD_NUMBER;
    hash = (53 * hash) + getStatusText().hashCode();
    hash = (37 * hash) + THIRDCODE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getThirdCode());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.textrcs.gmproto.conversations.MessageStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.conversations.MessageStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.conversations.MessageStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.conversations.MessageStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.conversations.MessageStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.conversations.MessageStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.conversations.MessageStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.conversations.MessageStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.textrcs.gmproto.conversations.MessageStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.conversations.MessageStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.textrcs.gmproto.conversations.MessageStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.conversations.MessageStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.textrcs.gmproto.conversations.MessageStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code conversations.MessageStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:conversations.MessageStatus)
      com.textrcs.gmproto.conversations.MessageStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.textrcs.gmproto.conversations.Conversations.internal_static_conversations_MessageStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.textrcs.gmproto.conversations.Conversations.internal_static_conversations_MessageStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.textrcs.gmproto.conversations.MessageStatus.class, com.textrcs.gmproto.conversations.MessageStatus.Builder.class);
    }

    // Construct using com.textrcs.gmproto.conversations.MessageStatus.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      status_ = 0;
      subCode_ = 0L;
      errMsg_ = "";
      statusText_ = "";
      thirdCode_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.textrcs.gmproto.conversations.Conversations.internal_static_conversations_MessageStatus_descriptor;
    }

    @java.lang.Override
    public com.textrcs.gmproto.conversations.MessageStatus getDefaultInstanceForType() {
      return com.textrcs.gmproto.conversations.MessageStatus.getDefaultInstance();
    }

    @java.lang.Override
    public com.textrcs.gmproto.conversations.MessageStatus build() {
      com.textrcs.gmproto.conversations.MessageStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.textrcs.gmproto.conversations.MessageStatus buildPartial() {
      com.textrcs.gmproto.conversations.MessageStatus result = new com.textrcs.gmproto.conversations.MessageStatus(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.textrcs.gmproto.conversations.MessageStatus result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.subCode_ = subCode_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.errMsg_ = errMsg_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.statusText_ = statusText_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.thirdCode_ = thirdCode_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.textrcs.gmproto.conversations.MessageStatus) {
        return mergeFrom((com.textrcs.gmproto.conversations.MessageStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.textrcs.gmproto.conversations.MessageStatus other) {
      if (other == com.textrcs.gmproto.conversations.MessageStatus.getDefaultInstance()) return this;
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.getSubCode() != 0L) {
        setSubCode(other.getSubCode());
      }
      if (!other.getErrMsg().isEmpty()) {
        errMsg_ = other.errMsg_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getStatusText().isEmpty()) {
        statusText_ = other.statusText_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getThirdCode() != 0L) {
        setThirdCode(other.getThirdCode());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 16: {
              status_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 16
            case 24: {
              subCode_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 24
            case 34: {
              errMsg_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 34
            case 42: {
              statusText_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 42
            case 48: {
              thirdCode_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int status_ = 0;
    /**
     * <code>.conversations.MessageStatusType status = 2;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.conversations.MessageStatusType status = 2;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.conversations.MessageStatusType status = 2;</code>
     * @return The status.
     */
    @java.lang.Override
    public com.textrcs.gmproto.conversations.MessageStatusType getStatus() {
      com.textrcs.gmproto.conversations.MessageStatusType result = com.textrcs.gmproto.conversations.MessageStatusType.forNumber(status_);
      return result == null ? com.textrcs.gmproto.conversations.MessageStatusType.UNRECOGNIZED : result;
    }
    /**
     * <code>.conversations.MessageStatusType status = 2;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(com.textrcs.gmproto.conversations.MessageStatusType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.conversations.MessageStatusType status = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000001);
      status_ = 0;
      onChanged();
      return this;
    }

    private long subCode_ ;
    /**
     * <code>int64 subCode = 3;</code>
     * @return The subCode.
     */
    @java.lang.Override
    public long getSubCode() {
      return subCode_;
    }
    /**
     * <code>int64 subCode = 3;</code>
     * @param value The subCode to set.
     * @return This builder for chaining.
     */
    public Builder setSubCode(long value) {
      
      subCode_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 subCode = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSubCode() {
      bitField0_ = (bitField0_ & ~0x00000002);
      subCode_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object errMsg_ = "";
    /**
     * <code>string errMsg = 4;</code>
     * @return The errMsg.
     */
    public java.lang.String getErrMsg() {
      java.lang.Object ref = errMsg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errMsg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string errMsg = 4;</code>
     * @return The bytes for errMsg.
     */
    public com.google.protobuf.ByteString
        getErrMsgBytes() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string errMsg = 4;</code>
     * @param value The errMsg to set.
     * @return This builder for chaining.
     */
    public Builder setErrMsg(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      errMsg_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string errMsg = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrMsg() {
      errMsg_ = getDefaultInstance().getErrMsg();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string errMsg = 4;</code>
     * @param value The bytes for errMsg to set.
     * @return This builder for chaining.
     */
    public Builder setErrMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      errMsg_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object statusText_ = "";
    /**
     * <code>string statusText = 5;</code>
     * @return The statusText.
     */
    public java.lang.String getStatusText() {
      java.lang.Object ref = statusText_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        statusText_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string statusText = 5;</code>
     * @return The bytes for statusText.
     */
    public com.google.protobuf.ByteString
        getStatusTextBytes() {
      java.lang.Object ref = statusText_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        statusText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string statusText = 5;</code>
     * @param value The statusText to set.
     * @return This builder for chaining.
     */
    public Builder setStatusText(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      statusText_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string statusText = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatusText() {
      statusText_ = getDefaultInstance().getStatusText();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string statusText = 5;</code>
     * @param value The bytes for statusText to set.
     * @return This builder for chaining.
     */
    public Builder setStatusTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      statusText_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private long thirdCode_ ;
    /**
     * <code>int64 thirdCode = 6;</code>
     * @return The thirdCode.
     */
    @java.lang.Override
    public long getThirdCode() {
      return thirdCode_;
    }
    /**
     * <code>int64 thirdCode = 6;</code>
     * @param value The thirdCode to set.
     * @return This builder for chaining.
     */
    public Builder setThirdCode(long value) {
      
      thirdCode_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int64 thirdCode = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearThirdCode() {
      bitField0_ = (bitField0_ & ~0x00000010);
      thirdCode_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:conversations.MessageStatus)
  }

  // @@protoc_insertion_point(class_scope:conversations.MessageStatus)
  private static final com.textrcs.gmproto.conversations.MessageStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.textrcs.gmproto.conversations.MessageStatus();
  }

  public static com.textrcs.gmproto.conversations.MessageStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MessageStatus>
      PARSER = new com.google.protobuf.AbstractParser<MessageStatus>() {
    @java.lang.Override
    public MessageStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MessageStatus> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MessageStatus> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.textrcs.gmproto.conversations.MessageStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

