// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: conversations.proto

package com.textrcs.gmproto.conversations;

public interface ParticipantOrBuilder extends
    // @@protoc_insertion_point(interface_extends:conversations.Participant)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.conversations.SmallInfo ID = 1;</code>
   * @return Whether the iD field is set.
   */
  boolean hasID();
  /**
   * <code>.conversations.SmallInfo ID = 1;</code>
   * @return The iD.
   */
  com.textrcs.gmproto.conversations.SmallInfo getID();
  /**
   * <code>.conversations.SmallInfo ID = 1;</code>
   */
  com.textrcs.gmproto.conversations.SmallInfoOrBuilder getIDOrBuilder();

  /**
   * <code>string firstName = 2;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string firstName = 2;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string fullName = 3;</code>
   * @return The fullName.
   */
  java.lang.String getFullName();
  /**
   * <code>string fullName = 3;</code>
   * @return The bytes for fullName.
   */
  com.google.protobuf.ByteString
      getFullNameBytes();

  /**
   * <code>string avatarHexColor = 5;</code>
   * @return The avatarHexColor.
   */
  java.lang.String getAvatarHexColor();
  /**
   * <code>string avatarHexColor = 5;</code>
   * @return The bytes for avatarHexColor.
   */
  com.google.protobuf.ByteString
      getAvatarHexColorBytes();

  /**
   * <code>bool isMe = 6;</code>
   * @return The isMe.
   */
  boolean getIsMe();

  /**
   * <code>.settings.SIMPayload simPayload = 7;</code>
   * @return Whether the simPayload field is set.
   */
  boolean hasSimPayload();
  /**
   * <code>.settings.SIMPayload simPayload = 7;</code>
   * @return The simPayload.
   */
  com.textrcs.gmproto.settings.SIMPayload getSimPayload();
  /**
   * <code>.settings.SIMPayload simPayload = 7;</code>
   */
  com.textrcs.gmproto.settings.SIMPayloadOrBuilder getSimPayloadOrBuilder();

  /**
   * <code>bool isVisible = 8;</code>
   * @return The isVisible.
   */
  boolean getIsVisible();

  /**
   * <code>string contactID = 10;</code>
   * @return The contactID.
   */
  java.lang.String getContactID();
  /**
   * <code>string contactID = 10;</code>
   * @return The bytes for contactID.
   */
  com.google.protobuf.ByteString
      getContactIDBytes();

  /**
   * <code>int64 bs = 14;</code>
   * @return The bs.
   */
  long getBs();

  /**
   * <code>string formattedNumber = 15;</code>
   * @return The formattedNumber.
   */
  java.lang.String getFormattedNumber();
  /**
   * <code>string formattedNumber = 15;</code>
   * @return The bytes for formattedNumber.
   */
  com.google.protobuf.ByteString
      getFormattedNumberBytes();

  /**
   * <code>int64 someInt1 = 19;</code>
   * @return The someInt1.
   */
  long getSomeInt1();

  /**
   * <code>int64 someInt2 = 20;</code>
   * @return The someInt2.
   */
  long getSomeInt2();
}
