// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: conversations.proto

package com.textrcs.gmproto.conversations;

public interface MsgTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:conversations.MsgType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 type = 1;</code>
   * @return The type.
   */
  long getType();
}
