// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: conversations.proto

package com.textrcs.gmproto.conversations;

/**
 * Protobuf type {@code conversations.ReactionEntry}
 */
public final class ReactionEntry extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:conversations.ReactionEntry)
    ReactionEntryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReactionEntry.newBuilder() to construct.
  private ReactionEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReactionEntry() {
    participantIDs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ReactionEntry();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.textrcs.gmproto.conversations.Conversations.internal_static_conversations_ReactionEntry_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.textrcs.gmproto.conversations.Conversations.internal_static_conversations_ReactionEntry_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.textrcs.gmproto.conversations.ReactionEntry.class, com.textrcs.gmproto.conversations.ReactionEntry.Builder.class);
  }

  public static final int DATA_FIELD_NUMBER = 1;
  private com.textrcs.gmproto.conversations.ReactionData data_;
  /**
   * <code>.conversations.ReactionData data = 1;</code>
   * @return Whether the data field is set.
   */
  @java.lang.Override
  public boolean hasData() {
    return data_ != null;
  }
  /**
   * <code>.conversations.ReactionData data = 1;</code>
   * @return The data.
   */
  @java.lang.Override
  public com.textrcs.gmproto.conversations.ReactionData getData() {
    return data_ == null ? com.textrcs.gmproto.conversations.ReactionData.getDefaultInstance() : data_;
  }
  /**
   * <code>.conversations.ReactionData data = 1;</code>
   */
  @java.lang.Override
  public com.textrcs.gmproto.conversations.ReactionDataOrBuilder getDataOrBuilder() {
    return data_ == null ? com.textrcs.gmproto.conversations.ReactionData.getDefaultInstance() : data_;
  }

  public static final int PARTICIPANTIDS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringList participantIDs_;
  /**
   * <code>repeated string participantIDs = 2;</code>
   * @return A list containing the participantIDs.
   */
  public com.google.protobuf.ProtocolStringList
      getParticipantIDsList() {
    return participantIDs_;
  }
  /**
   * <code>repeated string participantIDs = 2;</code>
   * @return The count of participantIDs.
   */
  public int getParticipantIDsCount() {
    return participantIDs_.size();
  }
  /**
   * <code>repeated string participantIDs = 2;</code>
   * @param index The index of the element to return.
   * @return The participantIDs at the given index.
   */
  public java.lang.String getParticipantIDs(int index) {
    return participantIDs_.get(index);
  }
  /**
   * <code>repeated string participantIDs = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the participantIDs at the given index.
   */
  public com.google.protobuf.ByteString
      getParticipantIDsBytes(int index) {
    return participantIDs_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (data_ != null) {
      output.writeMessage(1, getData());
    }
    for (int i = 0; i < participantIDs_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, participantIDs_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (data_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getData());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < participantIDs_.size(); i++) {
        dataSize += computeStringSizeNoTag(participantIDs_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getParticipantIDsList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.textrcs.gmproto.conversations.ReactionEntry)) {
      return super.equals(obj);
    }
    com.textrcs.gmproto.conversations.ReactionEntry other = (com.textrcs.gmproto.conversations.ReactionEntry) obj;

    if (hasData() != other.hasData()) return false;
    if (hasData()) {
      if (!getData()
          .equals(other.getData())) return false;
    }
    if (!getParticipantIDsList()
        .equals(other.getParticipantIDsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasData()) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
    }
    if (getParticipantIDsCount() > 0) {
      hash = (37 * hash) + PARTICIPANTIDS_FIELD_NUMBER;
      hash = (53 * hash) + getParticipantIDsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.textrcs.gmproto.conversations.ReactionEntry parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.conversations.ReactionEntry parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.conversations.ReactionEntry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.conversations.ReactionEntry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.conversations.ReactionEntry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.conversations.ReactionEntry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.conversations.ReactionEntry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.conversations.ReactionEntry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.textrcs.gmproto.conversations.ReactionEntry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.conversations.ReactionEntry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.textrcs.gmproto.conversations.ReactionEntry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.conversations.ReactionEntry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.textrcs.gmproto.conversations.ReactionEntry prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code conversations.ReactionEntry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:conversations.ReactionEntry)
      com.textrcs.gmproto.conversations.ReactionEntryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.textrcs.gmproto.conversations.Conversations.internal_static_conversations_ReactionEntry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.textrcs.gmproto.conversations.Conversations.internal_static_conversations_ReactionEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.textrcs.gmproto.conversations.ReactionEntry.class, com.textrcs.gmproto.conversations.ReactionEntry.Builder.class);
    }

    // Construct using com.textrcs.gmproto.conversations.ReactionEntry.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      data_ = null;
      if (dataBuilder_ != null) {
        dataBuilder_.dispose();
        dataBuilder_ = null;
      }
      participantIDs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.textrcs.gmproto.conversations.Conversations.internal_static_conversations_ReactionEntry_descriptor;
    }

    @java.lang.Override
    public com.textrcs.gmproto.conversations.ReactionEntry getDefaultInstanceForType() {
      return com.textrcs.gmproto.conversations.ReactionEntry.getDefaultInstance();
    }

    @java.lang.Override
    public com.textrcs.gmproto.conversations.ReactionEntry build() {
      com.textrcs.gmproto.conversations.ReactionEntry result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.textrcs.gmproto.conversations.ReactionEntry buildPartial() {
      com.textrcs.gmproto.conversations.ReactionEntry result = new com.textrcs.gmproto.conversations.ReactionEntry(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.textrcs.gmproto.conversations.ReactionEntry result) {
      if (((bitField0_ & 0x00000002) != 0)) {
        participantIDs_ = participantIDs_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.participantIDs_ = participantIDs_;
    }

    private void buildPartial0(com.textrcs.gmproto.conversations.ReactionEntry result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.data_ = dataBuilder_ == null
            ? data_
            : dataBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.textrcs.gmproto.conversations.ReactionEntry) {
        return mergeFrom((com.textrcs.gmproto.conversations.ReactionEntry)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.textrcs.gmproto.conversations.ReactionEntry other) {
      if (other == com.textrcs.gmproto.conversations.ReactionEntry.getDefaultInstance()) return this;
      if (other.hasData()) {
        mergeData(other.getData());
      }
      if (!other.participantIDs_.isEmpty()) {
        if (participantIDs_.isEmpty()) {
          participantIDs_ = other.participantIDs_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureParticipantIDsIsMutable();
          participantIDs_.addAll(other.participantIDs_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getDataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureParticipantIDsIsMutable();
              participantIDs_.add(s);
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.textrcs.gmproto.conversations.ReactionData data_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.textrcs.gmproto.conversations.ReactionData, com.textrcs.gmproto.conversations.ReactionData.Builder, com.textrcs.gmproto.conversations.ReactionDataOrBuilder> dataBuilder_;
    /**
     * <code>.conversations.ReactionData data = 1;</code>
     * @return Whether the data field is set.
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.conversations.ReactionData data = 1;</code>
     * @return The data.
     */
    public com.textrcs.gmproto.conversations.ReactionData getData() {
      if (dataBuilder_ == null) {
        return data_ == null ? com.textrcs.gmproto.conversations.ReactionData.getDefaultInstance() : data_;
      } else {
        return dataBuilder_.getMessage();
      }
    }
    /**
     * <code>.conversations.ReactionData data = 1;</code>
     */
    public Builder setData(com.textrcs.gmproto.conversations.ReactionData value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
      } else {
        dataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.conversations.ReactionData data = 1;</code>
     */
    public Builder setData(
        com.textrcs.gmproto.conversations.ReactionData.Builder builderForValue) {
      if (dataBuilder_ == null) {
        data_ = builderForValue.build();
      } else {
        dataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.conversations.ReactionData data = 1;</code>
     */
    public Builder mergeData(com.textrcs.gmproto.conversations.ReactionData value) {
      if (dataBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          data_ != null &&
          data_ != com.textrcs.gmproto.conversations.ReactionData.getDefaultInstance()) {
          getDataBuilder().mergeFrom(value);
        } else {
          data_ = value;
        }
      } else {
        dataBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.conversations.ReactionData data = 1;</code>
     */
    public Builder clearData() {
      bitField0_ = (bitField0_ & ~0x00000001);
      data_ = null;
      if (dataBuilder_ != null) {
        dataBuilder_.dispose();
        dataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.conversations.ReactionData data = 1;</code>
     */
    public com.textrcs.gmproto.conversations.ReactionData.Builder getDataBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.conversations.ReactionData data = 1;</code>
     */
    public com.textrcs.gmproto.conversations.ReactionDataOrBuilder getDataOrBuilder() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilder();
      } else {
        return data_ == null ?
            com.textrcs.gmproto.conversations.ReactionData.getDefaultInstance() : data_;
      }
    }
    /**
     * <code>.conversations.ReactionData data = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.textrcs.gmproto.conversations.ReactionData, com.textrcs.gmproto.conversations.ReactionData.Builder, com.textrcs.gmproto.conversations.ReactionDataOrBuilder> 
        getDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.textrcs.gmproto.conversations.ReactionData, com.textrcs.gmproto.conversations.ReactionData.Builder, com.textrcs.gmproto.conversations.ReactionDataOrBuilder>(
                getData(),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }

    private com.google.protobuf.LazyStringList participantIDs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureParticipantIDsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        participantIDs_ = new com.google.protobuf.LazyStringArrayList(participantIDs_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string participantIDs = 2;</code>
     * @return A list containing the participantIDs.
     */
    public com.google.protobuf.ProtocolStringList
        getParticipantIDsList() {
      return participantIDs_.getUnmodifiableView();
    }
    /**
     * <code>repeated string participantIDs = 2;</code>
     * @return The count of participantIDs.
     */
    public int getParticipantIDsCount() {
      return participantIDs_.size();
    }
    /**
     * <code>repeated string participantIDs = 2;</code>
     * @param index The index of the element to return.
     * @return The participantIDs at the given index.
     */
    public java.lang.String getParticipantIDs(int index) {
      return participantIDs_.get(index);
    }
    /**
     * <code>repeated string participantIDs = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the participantIDs at the given index.
     */
    public com.google.protobuf.ByteString
        getParticipantIDsBytes(int index) {
      return participantIDs_.getByteString(index);
    }
    /**
     * <code>repeated string participantIDs = 2;</code>
     * @param index The index to set the value at.
     * @param value The participantIDs to set.
     * @return This builder for chaining.
     */
    public Builder setParticipantIDs(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureParticipantIDsIsMutable();
      participantIDs_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string participantIDs = 2;</code>
     * @param value The participantIDs to add.
     * @return This builder for chaining.
     */
    public Builder addParticipantIDs(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureParticipantIDsIsMutable();
      participantIDs_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string participantIDs = 2;</code>
     * @param values The participantIDs to add.
     * @return This builder for chaining.
     */
    public Builder addAllParticipantIDs(
        java.lang.Iterable<java.lang.String> values) {
      ensureParticipantIDsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, participantIDs_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string participantIDs = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearParticipantIDs() {
      participantIDs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string participantIDs = 2;</code>
     * @param value The bytes of the participantIDs to add.
     * @return This builder for chaining.
     */
    public Builder addParticipantIDsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureParticipantIDsIsMutable();
      participantIDs_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:conversations.ReactionEntry)
  }

  // @@protoc_insertion_point(class_scope:conversations.ReactionEntry)
  private static final com.textrcs.gmproto.conversations.ReactionEntry DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.textrcs.gmproto.conversations.ReactionEntry();
  }

  public static com.textrcs.gmproto.conversations.ReactionEntry getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReactionEntry>
      PARSER = new com.google.protobuf.AbstractParser<ReactionEntry>() {
    @java.lang.Override
    public ReactionEntry parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ReactionEntry> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReactionEntry> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.textrcs.gmproto.conversations.ReactionEntry getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

