// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package com.textrcs.gmproto.client;

public interface AckMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client.AckMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.authentication.AuthMessage authData = 1;</code>
   * @return Whether the authData field is set.
   */
  boolean hasAuthData();
  /**
   * <code>.authentication.AuthMessage authData = 1;</code>
   * @return The authData.
   */
  com.textrcs.gmproto.authentication.AuthMessage getAuthData();
  /**
   * <code>.authentication.AuthMessage authData = 1;</code>
   */
  com.textrcs.gmproto.authentication.AuthMessageOrBuilder getAuthDataOrBuilder();

  /**
   * <code>.util.EmptyArr emptyArr = 2;</code>
   * @return Whether the emptyArr field is set.
   */
  boolean hasEmptyArr();
  /**
   * <code>.util.EmptyArr emptyArr = 2;</code>
   * @return The emptyArr.
   */
  com.textrcs.gmproto.util.EmptyArr getEmptyArr();
  /**
   * <code>.util.EmptyArr emptyArr = 2;</code>
   */
  com.textrcs.gmproto.util.EmptyArrOrBuilder getEmptyArrOrBuilder();

  /**
   * <code>repeated .client.AckMessageRequest.Message acks = 4;</code>
   */
  java.util.List<com.textrcs.gmproto.client.AckMessageRequest.Message> 
      getAcksList();
  /**
   * <code>repeated .client.AckMessageRequest.Message acks = 4;</code>
   */
  com.textrcs.gmproto.client.AckMessageRequest.Message getAcks(int index);
  /**
   * <code>repeated .client.AckMessageRequest.Message acks = 4;</code>
   */
  int getAcksCount();
  /**
   * <code>repeated .client.AckMessageRequest.Message acks = 4;</code>
   */
  java.util.List<? extends com.textrcs.gmproto.client.AckMessageRequest.MessageOrBuilder> 
      getAcksOrBuilderList();
  /**
   * <code>repeated .client.AckMessageRequest.Message acks = 4;</code>
   */
  com.textrcs.gmproto.client.AckMessageRequest.MessageOrBuilder getAcksOrBuilder(
      int index);
}
