// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package com.textrcs.gmproto.client;

/**
 * Protobuf type {@code client.AckMessageRequest}
 */
public final class AckMessageRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:client.AckMessageRequest)
    AckMessageRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AckMessageRequest.newBuilder() to construct.
  private AckMessageRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AckMessageRequest() {
    acks_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AckMessageRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.textrcs.gmproto.client.Client.internal_static_client_AckMessageRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.textrcs.gmproto.client.Client.internal_static_client_AckMessageRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.textrcs.gmproto.client.AckMessageRequest.class, com.textrcs.gmproto.client.AckMessageRequest.Builder.class);
  }

  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:client.AckMessageRequest.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string requestID = 1;</code>
     * @return The requestID.
     */
    java.lang.String getRequestID();
    /**
     * <code>string requestID = 1;</code>
     * @return The bytes for requestID.
     */
    com.google.protobuf.ByteString
        getRequestIDBytes();

    /**
     * <code>.authentication.Device device = 2;</code>
     * @return Whether the device field is set.
     */
    boolean hasDevice();
    /**
     * <code>.authentication.Device device = 2;</code>
     * @return The device.
     */
    com.textrcs.gmproto.authentication.Device getDevice();
    /**
     * <code>.authentication.Device device = 2;</code>
     */
    com.textrcs.gmproto.authentication.DeviceOrBuilder getDeviceOrBuilder();
  }
  /**
   * Protobuf type {@code client.AckMessageRequest.Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:client.AckMessageRequest.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      requestID_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.textrcs.gmproto.client.Client.internal_static_client_AckMessageRequest_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.textrcs.gmproto.client.Client.internal_static_client_AckMessageRequest_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.textrcs.gmproto.client.AckMessageRequest.Message.class, com.textrcs.gmproto.client.AckMessageRequest.Message.Builder.class);
    }

    public static final int REQUESTID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object requestID_ = "";
    /**
     * <code>string requestID = 1;</code>
     * @return The requestID.
     */
    @java.lang.Override
    public java.lang.String getRequestID() {
      java.lang.Object ref = requestID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestID_ = s;
        return s;
      }
    }
    /**
     * <code>string requestID = 1;</code>
     * @return The bytes for requestID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestIDBytes() {
      java.lang.Object ref = requestID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICE_FIELD_NUMBER = 2;
    private com.textrcs.gmproto.authentication.Device device_;
    /**
     * <code>.authentication.Device device = 2;</code>
     * @return Whether the device field is set.
     */
    @java.lang.Override
    public boolean hasDevice() {
      return device_ != null;
    }
    /**
     * <code>.authentication.Device device = 2;</code>
     * @return The device.
     */
    @java.lang.Override
    public com.textrcs.gmproto.authentication.Device getDevice() {
      return device_ == null ? com.textrcs.gmproto.authentication.Device.getDefaultInstance() : device_;
    }
    /**
     * <code>.authentication.Device device = 2;</code>
     */
    @java.lang.Override
    public com.textrcs.gmproto.authentication.DeviceOrBuilder getDeviceOrBuilder() {
      return device_ == null ? com.textrcs.gmproto.authentication.Device.getDefaultInstance() : device_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestID_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestID_);
      }
      if (device_ != null) {
        output.writeMessage(2, getDevice());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestID_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestID_);
      }
      if (device_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getDevice());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.textrcs.gmproto.client.AckMessageRequest.Message)) {
        return super.equals(obj);
      }
      com.textrcs.gmproto.client.AckMessageRequest.Message other = (com.textrcs.gmproto.client.AckMessageRequest.Message) obj;

      if (!getRequestID()
          .equals(other.getRequestID())) return false;
      if (hasDevice() != other.hasDevice()) return false;
      if (hasDevice()) {
        if (!getDevice()
            .equals(other.getDevice())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestID().hashCode();
      if (hasDevice()) {
        hash = (37 * hash) + DEVICE_FIELD_NUMBER;
        hash = (53 * hash) + getDevice().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.textrcs.gmproto.client.AckMessageRequest.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.textrcs.gmproto.client.AckMessageRequest.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.textrcs.gmproto.client.AckMessageRequest.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.textrcs.gmproto.client.AckMessageRequest.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.textrcs.gmproto.client.AckMessageRequest.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.textrcs.gmproto.client.AckMessageRequest.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.textrcs.gmproto.client.AckMessageRequest.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.textrcs.gmproto.client.AckMessageRequest.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.textrcs.gmproto.client.AckMessageRequest.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.textrcs.gmproto.client.AckMessageRequest.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.textrcs.gmproto.client.AckMessageRequest.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.textrcs.gmproto.client.AckMessageRequest.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.textrcs.gmproto.client.AckMessageRequest.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code client.AckMessageRequest.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:client.AckMessageRequest.Message)
        com.textrcs.gmproto.client.AckMessageRequest.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.textrcs.gmproto.client.Client.internal_static_client_AckMessageRequest_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.textrcs.gmproto.client.Client.internal_static_client_AckMessageRequest_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.textrcs.gmproto.client.AckMessageRequest.Message.class, com.textrcs.gmproto.client.AckMessageRequest.Message.Builder.class);
      }

      // Construct using com.textrcs.gmproto.client.AckMessageRequest.Message.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        requestID_ = "";
        device_ = null;
        if (deviceBuilder_ != null) {
          deviceBuilder_.dispose();
          deviceBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.textrcs.gmproto.client.Client.internal_static_client_AckMessageRequest_Message_descriptor;
      }

      @java.lang.Override
      public com.textrcs.gmproto.client.AckMessageRequest.Message getDefaultInstanceForType() {
        return com.textrcs.gmproto.client.AckMessageRequest.Message.getDefaultInstance();
      }

      @java.lang.Override
      public com.textrcs.gmproto.client.AckMessageRequest.Message build() {
        com.textrcs.gmproto.client.AckMessageRequest.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.textrcs.gmproto.client.AckMessageRequest.Message buildPartial() {
        com.textrcs.gmproto.client.AckMessageRequest.Message result = new com.textrcs.gmproto.client.AckMessageRequest.Message(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.textrcs.gmproto.client.AckMessageRequest.Message result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.requestID_ = requestID_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.device_ = deviceBuilder_ == null
              ? device_
              : deviceBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.textrcs.gmproto.client.AckMessageRequest.Message) {
          return mergeFrom((com.textrcs.gmproto.client.AckMessageRequest.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.textrcs.gmproto.client.AckMessageRequest.Message other) {
        if (other == com.textrcs.gmproto.client.AckMessageRequest.Message.getDefaultInstance()) return this;
        if (!other.getRequestID().isEmpty()) {
          requestID_ = other.requestID_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasDevice()) {
          mergeDevice(other.getDevice());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                requestID_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getDeviceFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object requestID_ = "";
      /**
       * <code>string requestID = 1;</code>
       * @return The requestID.
       */
      public java.lang.String getRequestID() {
        java.lang.Object ref = requestID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string requestID = 1;</code>
       * @return The bytes for requestID.
       */
      public com.google.protobuf.ByteString
          getRequestIDBytes() {
        java.lang.Object ref = requestID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string requestID = 1;</code>
       * @param value The requestID to set.
       * @return This builder for chaining.
       */
      public Builder setRequestID(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        requestID_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string requestID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestID() {
        requestID_ = getDefaultInstance().getRequestID();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string requestID = 1;</code>
       * @param value The bytes for requestID to set.
       * @return This builder for chaining.
       */
      public Builder setRequestIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        requestID_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.textrcs.gmproto.authentication.Device device_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.textrcs.gmproto.authentication.Device, com.textrcs.gmproto.authentication.Device.Builder, com.textrcs.gmproto.authentication.DeviceOrBuilder> deviceBuilder_;
      /**
       * <code>.authentication.Device device = 2;</code>
       * @return Whether the device field is set.
       */
      public boolean hasDevice() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.authentication.Device device = 2;</code>
       * @return The device.
       */
      public com.textrcs.gmproto.authentication.Device getDevice() {
        if (deviceBuilder_ == null) {
          return device_ == null ? com.textrcs.gmproto.authentication.Device.getDefaultInstance() : device_;
        } else {
          return deviceBuilder_.getMessage();
        }
      }
      /**
       * <code>.authentication.Device device = 2;</code>
       */
      public Builder setDevice(com.textrcs.gmproto.authentication.Device value) {
        if (deviceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          device_ = value;
        } else {
          deviceBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.authentication.Device device = 2;</code>
       */
      public Builder setDevice(
          com.textrcs.gmproto.authentication.Device.Builder builderForValue) {
        if (deviceBuilder_ == null) {
          device_ = builderForValue.build();
        } else {
          deviceBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.authentication.Device device = 2;</code>
       */
      public Builder mergeDevice(com.textrcs.gmproto.authentication.Device value) {
        if (deviceBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            device_ != null &&
            device_ != com.textrcs.gmproto.authentication.Device.getDefaultInstance()) {
            getDeviceBuilder().mergeFrom(value);
          } else {
            device_ = value;
          }
        } else {
          deviceBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.authentication.Device device = 2;</code>
       */
      public Builder clearDevice() {
        bitField0_ = (bitField0_ & ~0x00000002);
        device_ = null;
        if (deviceBuilder_ != null) {
          deviceBuilder_.dispose();
          deviceBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.authentication.Device device = 2;</code>
       */
      public com.textrcs.gmproto.authentication.Device.Builder getDeviceBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getDeviceFieldBuilder().getBuilder();
      }
      /**
       * <code>.authentication.Device device = 2;</code>
       */
      public com.textrcs.gmproto.authentication.DeviceOrBuilder getDeviceOrBuilder() {
        if (deviceBuilder_ != null) {
          return deviceBuilder_.getMessageOrBuilder();
        } else {
          return device_ == null ?
              com.textrcs.gmproto.authentication.Device.getDefaultInstance() : device_;
        }
      }
      /**
       * <code>.authentication.Device device = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.textrcs.gmproto.authentication.Device, com.textrcs.gmproto.authentication.Device.Builder, com.textrcs.gmproto.authentication.DeviceOrBuilder> 
          getDeviceFieldBuilder() {
        if (deviceBuilder_ == null) {
          deviceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.textrcs.gmproto.authentication.Device, com.textrcs.gmproto.authentication.Device.Builder, com.textrcs.gmproto.authentication.DeviceOrBuilder>(
                  getDevice(),
                  getParentForChildren(),
                  isClean());
          device_ = null;
        }
        return deviceBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:client.AckMessageRequest.Message)
    }

    // @@protoc_insertion_point(class_scope:client.AckMessageRequest.Message)
    private static final com.textrcs.gmproto.client.AckMessageRequest.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.textrcs.gmproto.client.AckMessageRequest.Message();
    }

    public static com.textrcs.gmproto.client.AckMessageRequest.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.textrcs.gmproto.client.AckMessageRequest.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int AUTHDATA_FIELD_NUMBER = 1;
  private com.textrcs.gmproto.authentication.AuthMessage authData_;
  /**
   * <code>.authentication.AuthMessage authData = 1;</code>
   * @return Whether the authData field is set.
   */
  @java.lang.Override
  public boolean hasAuthData() {
    return authData_ != null;
  }
  /**
   * <code>.authentication.AuthMessage authData = 1;</code>
   * @return The authData.
   */
  @java.lang.Override
  public com.textrcs.gmproto.authentication.AuthMessage getAuthData() {
    return authData_ == null ? com.textrcs.gmproto.authentication.AuthMessage.getDefaultInstance() : authData_;
  }
  /**
   * <code>.authentication.AuthMessage authData = 1;</code>
   */
  @java.lang.Override
  public com.textrcs.gmproto.authentication.AuthMessageOrBuilder getAuthDataOrBuilder() {
    return authData_ == null ? com.textrcs.gmproto.authentication.AuthMessage.getDefaultInstance() : authData_;
  }

  public static final int EMPTYARR_FIELD_NUMBER = 2;
  private com.textrcs.gmproto.util.EmptyArr emptyArr_;
  /**
   * <code>.util.EmptyArr emptyArr = 2;</code>
   * @return Whether the emptyArr field is set.
   */
  @java.lang.Override
  public boolean hasEmptyArr() {
    return emptyArr_ != null;
  }
  /**
   * <code>.util.EmptyArr emptyArr = 2;</code>
   * @return The emptyArr.
   */
  @java.lang.Override
  public com.textrcs.gmproto.util.EmptyArr getEmptyArr() {
    return emptyArr_ == null ? com.textrcs.gmproto.util.EmptyArr.getDefaultInstance() : emptyArr_;
  }
  /**
   * <code>.util.EmptyArr emptyArr = 2;</code>
   */
  @java.lang.Override
  public com.textrcs.gmproto.util.EmptyArrOrBuilder getEmptyArrOrBuilder() {
    return emptyArr_ == null ? com.textrcs.gmproto.util.EmptyArr.getDefaultInstance() : emptyArr_;
  }

  public static final int ACKS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<com.textrcs.gmproto.client.AckMessageRequest.Message> acks_;
  /**
   * <code>repeated .client.AckMessageRequest.Message acks = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.textrcs.gmproto.client.AckMessageRequest.Message> getAcksList() {
    return acks_;
  }
  /**
   * <code>repeated .client.AckMessageRequest.Message acks = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.textrcs.gmproto.client.AckMessageRequest.MessageOrBuilder> 
      getAcksOrBuilderList() {
    return acks_;
  }
  /**
   * <code>repeated .client.AckMessageRequest.Message acks = 4;</code>
   */
  @java.lang.Override
  public int getAcksCount() {
    return acks_.size();
  }
  /**
   * <code>repeated .client.AckMessageRequest.Message acks = 4;</code>
   */
  @java.lang.Override
  public com.textrcs.gmproto.client.AckMessageRequest.Message getAcks(int index) {
    return acks_.get(index);
  }
  /**
   * <code>repeated .client.AckMessageRequest.Message acks = 4;</code>
   */
  @java.lang.Override
  public com.textrcs.gmproto.client.AckMessageRequest.MessageOrBuilder getAcksOrBuilder(
      int index) {
    return acks_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (authData_ != null) {
      output.writeMessage(1, getAuthData());
    }
    if (emptyArr_ != null) {
      output.writeMessage(2, getEmptyArr());
    }
    for (int i = 0; i < acks_.size(); i++) {
      output.writeMessage(4, acks_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (authData_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getAuthData());
    }
    if (emptyArr_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getEmptyArr());
    }
    for (int i = 0; i < acks_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, acks_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.textrcs.gmproto.client.AckMessageRequest)) {
      return super.equals(obj);
    }
    com.textrcs.gmproto.client.AckMessageRequest other = (com.textrcs.gmproto.client.AckMessageRequest) obj;

    if (hasAuthData() != other.hasAuthData()) return false;
    if (hasAuthData()) {
      if (!getAuthData()
          .equals(other.getAuthData())) return false;
    }
    if (hasEmptyArr() != other.hasEmptyArr()) return false;
    if (hasEmptyArr()) {
      if (!getEmptyArr()
          .equals(other.getEmptyArr())) return false;
    }
    if (!getAcksList()
        .equals(other.getAcksList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAuthData()) {
      hash = (37 * hash) + AUTHDATA_FIELD_NUMBER;
      hash = (53 * hash) + getAuthData().hashCode();
    }
    if (hasEmptyArr()) {
      hash = (37 * hash) + EMPTYARR_FIELD_NUMBER;
      hash = (53 * hash) + getEmptyArr().hashCode();
    }
    if (getAcksCount() > 0) {
      hash = (37 * hash) + ACKS_FIELD_NUMBER;
      hash = (53 * hash) + getAcksList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.textrcs.gmproto.client.AckMessageRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.client.AckMessageRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.client.AckMessageRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.client.AckMessageRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.client.AckMessageRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.client.AckMessageRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.client.AckMessageRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.client.AckMessageRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.textrcs.gmproto.client.AckMessageRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.client.AckMessageRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.textrcs.gmproto.client.AckMessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.client.AckMessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.textrcs.gmproto.client.AckMessageRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code client.AckMessageRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:client.AckMessageRequest)
      com.textrcs.gmproto.client.AckMessageRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.textrcs.gmproto.client.Client.internal_static_client_AckMessageRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.textrcs.gmproto.client.Client.internal_static_client_AckMessageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.textrcs.gmproto.client.AckMessageRequest.class, com.textrcs.gmproto.client.AckMessageRequest.Builder.class);
    }

    // Construct using com.textrcs.gmproto.client.AckMessageRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      authData_ = null;
      if (authDataBuilder_ != null) {
        authDataBuilder_.dispose();
        authDataBuilder_ = null;
      }
      emptyArr_ = null;
      if (emptyArrBuilder_ != null) {
        emptyArrBuilder_.dispose();
        emptyArrBuilder_ = null;
      }
      if (acksBuilder_ == null) {
        acks_ = java.util.Collections.emptyList();
      } else {
        acks_ = null;
        acksBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.textrcs.gmproto.client.Client.internal_static_client_AckMessageRequest_descriptor;
    }

    @java.lang.Override
    public com.textrcs.gmproto.client.AckMessageRequest getDefaultInstanceForType() {
      return com.textrcs.gmproto.client.AckMessageRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.textrcs.gmproto.client.AckMessageRequest build() {
      com.textrcs.gmproto.client.AckMessageRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.textrcs.gmproto.client.AckMessageRequest buildPartial() {
      com.textrcs.gmproto.client.AckMessageRequest result = new com.textrcs.gmproto.client.AckMessageRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.textrcs.gmproto.client.AckMessageRequest result) {
      if (acksBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          acks_ = java.util.Collections.unmodifiableList(acks_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.acks_ = acks_;
      } else {
        result.acks_ = acksBuilder_.build();
      }
    }

    private void buildPartial0(com.textrcs.gmproto.client.AckMessageRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.authData_ = authDataBuilder_ == null
            ? authData_
            : authDataBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.emptyArr_ = emptyArrBuilder_ == null
            ? emptyArr_
            : emptyArrBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.textrcs.gmproto.client.AckMessageRequest) {
        return mergeFrom((com.textrcs.gmproto.client.AckMessageRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.textrcs.gmproto.client.AckMessageRequest other) {
      if (other == com.textrcs.gmproto.client.AckMessageRequest.getDefaultInstance()) return this;
      if (other.hasAuthData()) {
        mergeAuthData(other.getAuthData());
      }
      if (other.hasEmptyArr()) {
        mergeEmptyArr(other.getEmptyArr());
      }
      if (acksBuilder_ == null) {
        if (!other.acks_.isEmpty()) {
          if (acks_.isEmpty()) {
            acks_ = other.acks_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureAcksIsMutable();
            acks_.addAll(other.acks_);
          }
          onChanged();
        }
      } else {
        if (!other.acks_.isEmpty()) {
          if (acksBuilder_.isEmpty()) {
            acksBuilder_.dispose();
            acksBuilder_ = null;
            acks_ = other.acks_;
            bitField0_ = (bitField0_ & ~0x00000004);
            acksBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAcksFieldBuilder() : null;
          } else {
            acksBuilder_.addAllMessages(other.acks_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getAuthDataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getEmptyArrFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 34: {
              com.textrcs.gmproto.client.AckMessageRequest.Message m =
                  input.readMessage(
                      com.textrcs.gmproto.client.AckMessageRequest.Message.parser(),
                      extensionRegistry);
              if (acksBuilder_ == null) {
                ensureAcksIsMutable();
                acks_.add(m);
              } else {
                acksBuilder_.addMessage(m);
              }
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.textrcs.gmproto.authentication.AuthMessage authData_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.textrcs.gmproto.authentication.AuthMessage, com.textrcs.gmproto.authentication.AuthMessage.Builder, com.textrcs.gmproto.authentication.AuthMessageOrBuilder> authDataBuilder_;
    /**
     * <code>.authentication.AuthMessage authData = 1;</code>
     * @return Whether the authData field is set.
     */
    public boolean hasAuthData() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.authentication.AuthMessage authData = 1;</code>
     * @return The authData.
     */
    public com.textrcs.gmproto.authentication.AuthMessage getAuthData() {
      if (authDataBuilder_ == null) {
        return authData_ == null ? com.textrcs.gmproto.authentication.AuthMessage.getDefaultInstance() : authData_;
      } else {
        return authDataBuilder_.getMessage();
      }
    }
    /**
     * <code>.authentication.AuthMessage authData = 1;</code>
     */
    public Builder setAuthData(com.textrcs.gmproto.authentication.AuthMessage value) {
      if (authDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        authData_ = value;
      } else {
        authDataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.authentication.AuthMessage authData = 1;</code>
     */
    public Builder setAuthData(
        com.textrcs.gmproto.authentication.AuthMessage.Builder builderForValue) {
      if (authDataBuilder_ == null) {
        authData_ = builderForValue.build();
      } else {
        authDataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.authentication.AuthMessage authData = 1;</code>
     */
    public Builder mergeAuthData(com.textrcs.gmproto.authentication.AuthMessage value) {
      if (authDataBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          authData_ != null &&
          authData_ != com.textrcs.gmproto.authentication.AuthMessage.getDefaultInstance()) {
          getAuthDataBuilder().mergeFrom(value);
        } else {
          authData_ = value;
        }
      } else {
        authDataBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.authentication.AuthMessage authData = 1;</code>
     */
    public Builder clearAuthData() {
      bitField0_ = (bitField0_ & ~0x00000001);
      authData_ = null;
      if (authDataBuilder_ != null) {
        authDataBuilder_.dispose();
        authDataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.authentication.AuthMessage authData = 1;</code>
     */
    public com.textrcs.gmproto.authentication.AuthMessage.Builder getAuthDataBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getAuthDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.authentication.AuthMessage authData = 1;</code>
     */
    public com.textrcs.gmproto.authentication.AuthMessageOrBuilder getAuthDataOrBuilder() {
      if (authDataBuilder_ != null) {
        return authDataBuilder_.getMessageOrBuilder();
      } else {
        return authData_ == null ?
            com.textrcs.gmproto.authentication.AuthMessage.getDefaultInstance() : authData_;
      }
    }
    /**
     * <code>.authentication.AuthMessage authData = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.textrcs.gmproto.authentication.AuthMessage, com.textrcs.gmproto.authentication.AuthMessage.Builder, com.textrcs.gmproto.authentication.AuthMessageOrBuilder> 
        getAuthDataFieldBuilder() {
      if (authDataBuilder_ == null) {
        authDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.textrcs.gmproto.authentication.AuthMessage, com.textrcs.gmproto.authentication.AuthMessage.Builder, com.textrcs.gmproto.authentication.AuthMessageOrBuilder>(
                getAuthData(),
                getParentForChildren(),
                isClean());
        authData_ = null;
      }
      return authDataBuilder_;
    }

    private com.textrcs.gmproto.util.EmptyArr emptyArr_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.textrcs.gmproto.util.EmptyArr, com.textrcs.gmproto.util.EmptyArr.Builder, com.textrcs.gmproto.util.EmptyArrOrBuilder> emptyArrBuilder_;
    /**
     * <code>.util.EmptyArr emptyArr = 2;</code>
     * @return Whether the emptyArr field is set.
     */
    public boolean hasEmptyArr() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.util.EmptyArr emptyArr = 2;</code>
     * @return The emptyArr.
     */
    public com.textrcs.gmproto.util.EmptyArr getEmptyArr() {
      if (emptyArrBuilder_ == null) {
        return emptyArr_ == null ? com.textrcs.gmproto.util.EmptyArr.getDefaultInstance() : emptyArr_;
      } else {
        return emptyArrBuilder_.getMessage();
      }
    }
    /**
     * <code>.util.EmptyArr emptyArr = 2;</code>
     */
    public Builder setEmptyArr(com.textrcs.gmproto.util.EmptyArr value) {
      if (emptyArrBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        emptyArr_ = value;
      } else {
        emptyArrBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.util.EmptyArr emptyArr = 2;</code>
     */
    public Builder setEmptyArr(
        com.textrcs.gmproto.util.EmptyArr.Builder builderForValue) {
      if (emptyArrBuilder_ == null) {
        emptyArr_ = builderForValue.build();
      } else {
        emptyArrBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.util.EmptyArr emptyArr = 2;</code>
     */
    public Builder mergeEmptyArr(com.textrcs.gmproto.util.EmptyArr value) {
      if (emptyArrBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          emptyArr_ != null &&
          emptyArr_ != com.textrcs.gmproto.util.EmptyArr.getDefaultInstance()) {
          getEmptyArrBuilder().mergeFrom(value);
        } else {
          emptyArr_ = value;
        }
      } else {
        emptyArrBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.util.EmptyArr emptyArr = 2;</code>
     */
    public Builder clearEmptyArr() {
      bitField0_ = (bitField0_ & ~0x00000002);
      emptyArr_ = null;
      if (emptyArrBuilder_ != null) {
        emptyArrBuilder_.dispose();
        emptyArrBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.util.EmptyArr emptyArr = 2;</code>
     */
    public com.textrcs.gmproto.util.EmptyArr.Builder getEmptyArrBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getEmptyArrFieldBuilder().getBuilder();
    }
    /**
     * <code>.util.EmptyArr emptyArr = 2;</code>
     */
    public com.textrcs.gmproto.util.EmptyArrOrBuilder getEmptyArrOrBuilder() {
      if (emptyArrBuilder_ != null) {
        return emptyArrBuilder_.getMessageOrBuilder();
      } else {
        return emptyArr_ == null ?
            com.textrcs.gmproto.util.EmptyArr.getDefaultInstance() : emptyArr_;
      }
    }
    /**
     * <code>.util.EmptyArr emptyArr = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.textrcs.gmproto.util.EmptyArr, com.textrcs.gmproto.util.EmptyArr.Builder, com.textrcs.gmproto.util.EmptyArrOrBuilder> 
        getEmptyArrFieldBuilder() {
      if (emptyArrBuilder_ == null) {
        emptyArrBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.textrcs.gmproto.util.EmptyArr, com.textrcs.gmproto.util.EmptyArr.Builder, com.textrcs.gmproto.util.EmptyArrOrBuilder>(
                getEmptyArr(),
                getParentForChildren(),
                isClean());
        emptyArr_ = null;
      }
      return emptyArrBuilder_;
    }

    private java.util.List<com.textrcs.gmproto.client.AckMessageRequest.Message> acks_ =
      java.util.Collections.emptyList();
    private void ensureAcksIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        acks_ = new java.util.ArrayList<com.textrcs.gmproto.client.AckMessageRequest.Message>(acks_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.textrcs.gmproto.client.AckMessageRequest.Message, com.textrcs.gmproto.client.AckMessageRequest.Message.Builder, com.textrcs.gmproto.client.AckMessageRequest.MessageOrBuilder> acksBuilder_;

    /**
     * <code>repeated .client.AckMessageRequest.Message acks = 4;</code>
     */
    public java.util.List<com.textrcs.gmproto.client.AckMessageRequest.Message> getAcksList() {
      if (acksBuilder_ == null) {
        return java.util.Collections.unmodifiableList(acks_);
      } else {
        return acksBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .client.AckMessageRequest.Message acks = 4;</code>
     */
    public int getAcksCount() {
      if (acksBuilder_ == null) {
        return acks_.size();
      } else {
        return acksBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .client.AckMessageRequest.Message acks = 4;</code>
     */
    public com.textrcs.gmproto.client.AckMessageRequest.Message getAcks(int index) {
      if (acksBuilder_ == null) {
        return acks_.get(index);
      } else {
        return acksBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .client.AckMessageRequest.Message acks = 4;</code>
     */
    public Builder setAcks(
        int index, com.textrcs.gmproto.client.AckMessageRequest.Message value) {
      if (acksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAcksIsMutable();
        acks_.set(index, value);
        onChanged();
      } else {
        acksBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .client.AckMessageRequest.Message acks = 4;</code>
     */
    public Builder setAcks(
        int index, com.textrcs.gmproto.client.AckMessageRequest.Message.Builder builderForValue) {
      if (acksBuilder_ == null) {
        ensureAcksIsMutable();
        acks_.set(index, builderForValue.build());
        onChanged();
      } else {
        acksBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .client.AckMessageRequest.Message acks = 4;</code>
     */
    public Builder addAcks(com.textrcs.gmproto.client.AckMessageRequest.Message value) {
      if (acksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAcksIsMutable();
        acks_.add(value);
        onChanged();
      } else {
        acksBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .client.AckMessageRequest.Message acks = 4;</code>
     */
    public Builder addAcks(
        int index, com.textrcs.gmproto.client.AckMessageRequest.Message value) {
      if (acksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAcksIsMutable();
        acks_.add(index, value);
        onChanged();
      } else {
        acksBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .client.AckMessageRequest.Message acks = 4;</code>
     */
    public Builder addAcks(
        com.textrcs.gmproto.client.AckMessageRequest.Message.Builder builderForValue) {
      if (acksBuilder_ == null) {
        ensureAcksIsMutable();
        acks_.add(builderForValue.build());
        onChanged();
      } else {
        acksBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .client.AckMessageRequest.Message acks = 4;</code>
     */
    public Builder addAcks(
        int index, com.textrcs.gmproto.client.AckMessageRequest.Message.Builder builderForValue) {
      if (acksBuilder_ == null) {
        ensureAcksIsMutable();
        acks_.add(index, builderForValue.build());
        onChanged();
      } else {
        acksBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .client.AckMessageRequest.Message acks = 4;</code>
     */
    public Builder addAllAcks(
        java.lang.Iterable<? extends com.textrcs.gmproto.client.AckMessageRequest.Message> values) {
      if (acksBuilder_ == null) {
        ensureAcksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, acks_);
        onChanged();
      } else {
        acksBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .client.AckMessageRequest.Message acks = 4;</code>
     */
    public Builder clearAcks() {
      if (acksBuilder_ == null) {
        acks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        acksBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .client.AckMessageRequest.Message acks = 4;</code>
     */
    public Builder removeAcks(int index) {
      if (acksBuilder_ == null) {
        ensureAcksIsMutable();
        acks_.remove(index);
        onChanged();
      } else {
        acksBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .client.AckMessageRequest.Message acks = 4;</code>
     */
    public com.textrcs.gmproto.client.AckMessageRequest.Message.Builder getAcksBuilder(
        int index) {
      return getAcksFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .client.AckMessageRequest.Message acks = 4;</code>
     */
    public com.textrcs.gmproto.client.AckMessageRequest.MessageOrBuilder getAcksOrBuilder(
        int index) {
      if (acksBuilder_ == null) {
        return acks_.get(index);  } else {
        return acksBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .client.AckMessageRequest.Message acks = 4;</code>
     */
    public java.util.List<? extends com.textrcs.gmproto.client.AckMessageRequest.MessageOrBuilder> 
         getAcksOrBuilderList() {
      if (acksBuilder_ != null) {
        return acksBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(acks_);
      }
    }
    /**
     * <code>repeated .client.AckMessageRequest.Message acks = 4;</code>
     */
    public com.textrcs.gmproto.client.AckMessageRequest.Message.Builder addAcksBuilder() {
      return getAcksFieldBuilder().addBuilder(
          com.textrcs.gmproto.client.AckMessageRequest.Message.getDefaultInstance());
    }
    /**
     * <code>repeated .client.AckMessageRequest.Message acks = 4;</code>
     */
    public com.textrcs.gmproto.client.AckMessageRequest.Message.Builder addAcksBuilder(
        int index) {
      return getAcksFieldBuilder().addBuilder(
          index, com.textrcs.gmproto.client.AckMessageRequest.Message.getDefaultInstance());
    }
    /**
     * <code>repeated .client.AckMessageRequest.Message acks = 4;</code>
     */
    public java.util.List<com.textrcs.gmproto.client.AckMessageRequest.Message.Builder> 
         getAcksBuilderList() {
      return getAcksFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.textrcs.gmproto.client.AckMessageRequest.Message, com.textrcs.gmproto.client.AckMessageRequest.Message.Builder, com.textrcs.gmproto.client.AckMessageRequest.MessageOrBuilder> 
        getAcksFieldBuilder() {
      if (acksBuilder_ == null) {
        acksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.textrcs.gmproto.client.AckMessageRequest.Message, com.textrcs.gmproto.client.AckMessageRequest.Message.Builder, com.textrcs.gmproto.client.AckMessageRequest.MessageOrBuilder>(
                acks_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        acks_ = null;
      }
      return acksBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:client.AckMessageRequest)
  }

  // @@protoc_insertion_point(class_scope:client.AckMessageRequest)
  private static final com.textrcs.gmproto.client.AckMessageRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.textrcs.gmproto.client.AckMessageRequest();
  }

  public static com.textrcs.gmproto.client.AckMessageRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AckMessageRequest>
      PARSER = new com.google.protobuf.AbstractParser<AckMessageRequest>() {
    @java.lang.Override
    public AckMessageRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AckMessageRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AckMessageRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.textrcs.gmproto.client.AckMessageRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

