// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package com.textrcs.gmproto.client;

public interface ListTopContactsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client.ListTopContactsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 count = 1;</code>
   * @return The count.
   */
  int getCount();
}
