// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package com.textrcs.gmproto.client;

public interface NotifyDittoActivityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client.NotifyDittoActivityResponse)
    com.google.protobuf.MessageOrBuilder {
}
