// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package com.textrcs.gmproto.client;

public interface OpenConversationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client.OpenConversationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string conversationID = 2;</code>
   * @return The conversationID.
   */
  java.lang.String getConversationID();
  /**
   * <code>string conversationID = 2;</code>
   * @return The bytes for conversationID.
   */
  com.google.protobuf.ByteString
      getConversationIDBytes();
}
