// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package com.textrcs.gmproto.client;

public interface SendReactionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client.SendReactionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string messageID = 1;</code>
   * @return The messageID.
   */
  java.lang.String getMessageID();
  /**
   * <code>string messageID = 1;</code>
   * @return The bytes for messageID.
   */
  com.google.protobuf.ByteString
      getMessageIDBytes();

  /**
   * <code>.conversations.ReactionData reactionData = 2;</code>
   * @return Whether the reactionData field is set.
   */
  boolean hasReactionData();
  /**
   * <code>.conversations.ReactionData reactionData = 2;</code>
   * @return The reactionData.
   */
  com.textrcs.gmproto.conversations.ReactionData getReactionData();
  /**
   * <code>.conversations.ReactionData reactionData = 2;</code>
   */
  com.textrcs.gmproto.conversations.ReactionDataOrBuilder getReactionDataOrBuilder();

  /**
   * <code>.client.SendReactionRequest.Action action = 3;</code>
   * @return The enum numeric value on the wire for action.
   */
  int getActionValue();
  /**
   * <code>.client.SendReactionRequest.Action action = 3;</code>
   * @return The action.
   */
  com.textrcs.gmproto.client.SendReactionRequest.Action getAction();

  /**
   * <code>.settings.SIMPayload SIMPayload = 4;</code>
   * @return Whether the sIMPayload field is set.
   */
  boolean hasSIMPayload();
  /**
   * <code>.settings.SIMPayload SIMPayload = 4;</code>
   * @return The sIMPayload.
   */
  com.textrcs.gmproto.settings.SIMPayload getSIMPayload();
  /**
   * <code>.settings.SIMPayload SIMPayload = 4;</code>
   */
  com.textrcs.gmproto.settings.SIMPayloadOrBuilder getSIMPayloadOrBuilder();
}
