// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package com.textrcs.gmproto.client;

public interface TypingUpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client.TypingUpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.client.TypingUpdateRequest.Data data = 2;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.client.TypingUpdateRequest.Data data = 2;</code>
   * @return The data.
   */
  com.textrcs.gmproto.client.TypingUpdateRequest.Data getData();
  /**
   * <code>.client.TypingUpdateRequest.Data data = 2;</code>
   */
  com.textrcs.gmproto.client.TypingUpdateRequest.DataOrBuilder getDataOrBuilder();

  /**
   * <code>.settings.SIMPayload SIMPayload = 3;</code>
   * @return Whether the sIMPayload field is set.
   */
  boolean hasSIMPayload();
  /**
   * <code>.settings.SIMPayload SIMPayload = 3;</code>
   * @return The sIMPayload.
   */
  com.textrcs.gmproto.settings.SIMPayload getSIMPayload();
  /**
   * <code>.settings.SIMPayload SIMPayload = 3;</code>
   */
  com.textrcs.gmproto.settings.SIMPayloadOrBuilder getSIMPayloadOrBuilder();
}
