// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package com.textrcs.gmproto.client;

public interface UploadedMediaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client.UploadedMedia)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string mediaID = 1;</code>
   * @return The mediaID.
   */
  java.lang.String getMediaID();
  /**
   * <code>string mediaID = 1;</code>
   * @return The bytes for mediaID.
   */
  com.google.protobuf.ByteString
      getMediaIDBytes();

  /**
   * <code>int64 mediaNumber = 2;</code>
   * @return The mediaNumber.
   */
  long getMediaNumber();
}
