// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: settings.proto

package com.textrcs.gmproto.settings;

public interface RCSSettingsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:settings.RCSSettings)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isEnabled = 1;</code>
   * @return The isEnabled.
   */
  boolean getIsEnabled();

  /**
   * <code>bool sendReadReceipts = 2;</code>
   * @return The sendReadReceipts.
   */
  boolean getSendReadReceipts();

  /**
   * <code>bool showTypingIndicators = 3;</code>
   * @return The showTypingIndicators.
   */
  boolean getShowTypingIndicators();

  /**
   * <pre>
   * uncertain, but this field seems to disappear when gmessages is un-defaulted
   * </pre>
   *
   * <code>bool isDefaultSMSApp = 4;</code>
   * @return The isDefaultSMSApp.
   */
  boolean getIsDefaultSMSApp();
}
