// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ukey.proto

package com.textrcs.gmproto.ukey;

public interface DhPublicKeyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ukey.DhPublicKey)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Big-endian two's complement encoded group element
   * </pre>
   *
   * <code>bytes y = 1;</code>
   * @return The y.
   */
  com.google.protobuf.ByteString getY();
}
