// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ukey.proto

package com.textrcs.gmproto.ukey;

public interface EcP256PublicKeyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ukey.EcP256PublicKey)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * x and y are encoded in big-endian two's complement (slightly wasteful)
   * Client MUST verify (x,y) is a valid point on NIST P256
   * </pre>
   *
   * <code>bytes x = 1;</code>
   * @return The x.
   */
  com.google.protobuf.ByteString getX();

  /**
   * <code>bytes y = 2;</code>
   * @return The y.
   */
  com.google.protobuf.ByteString getY();
}
