// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ukey.proto

package com.textrcs.gmproto.ukey;

public interface GenericPublicKeyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ukey.GenericPublicKey)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ukey.PublicKeyType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.ukey.PublicKeyType type = 1;</code>
   * @return The type.
   */
  com.textrcs.gmproto.ukey.PublicKeyType getType();

  /**
   * <code>.ukey.EcP256PublicKey ec_p256_public_key = 2;</code>
   * @return Whether the ecP256PublicKey field is set.
   */
  boolean hasEcP256PublicKey();
  /**
   * <code>.ukey.EcP256PublicKey ec_p256_public_key = 2;</code>
   * @return The ecP256PublicKey.
   */
  com.textrcs.gmproto.ukey.EcP256PublicKey getEcP256PublicKey();
  /**
   * <code>.ukey.EcP256PublicKey ec_p256_public_key = 2;</code>
   */
  com.textrcs.gmproto.ukey.EcP256PublicKeyOrBuilder getEcP256PublicKeyOrBuilder();

  /**
   * <code>.ukey.SimpleRsaPublicKey rsa2048_public_key = 3;</code>
   * @return Whether the rsa2048PublicKey field is set.
   */
  boolean hasRsa2048PublicKey();
  /**
   * <code>.ukey.SimpleRsaPublicKey rsa2048_public_key = 3;</code>
   * @return The rsa2048PublicKey.
   */
  com.textrcs.gmproto.ukey.SimpleRsaPublicKey getRsa2048PublicKey();
  /**
   * <code>.ukey.SimpleRsaPublicKey rsa2048_public_key = 3;</code>
   */
  com.textrcs.gmproto.ukey.SimpleRsaPublicKeyOrBuilder getRsa2048PublicKeyOrBuilder();

  /**
   * <pre>
   * Use only as a last resort
   * </pre>
   *
   * <code>.ukey.DhPublicKey dh2048_public_key = 4;</code>
   * @return Whether the dh2048PublicKey field is set.
   */
  boolean hasDh2048PublicKey();
  /**
   * <pre>
   * Use only as a last resort
   * </pre>
   *
   * <code>.ukey.DhPublicKey dh2048_public_key = 4;</code>
   * @return The dh2048PublicKey.
   */
  com.textrcs.gmproto.ukey.DhPublicKey getDh2048PublicKey();
  /**
   * <pre>
   * Use only as a last resort
   * </pre>
   *
   * <code>.ukey.DhPublicKey dh2048_public_key = 4;</code>
   */
  com.textrcs.gmproto.ukey.DhPublicKeyOrBuilder getDh2048PublicKeyOrBuilder();

  public com.textrcs.gmproto.ukey.GenericPublicKey.PublicKeyCase getPublicKeyCase();
}
