// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ukey.proto

package com.textrcs.gmproto.ukey;

public interface SimpleRsaPublicKeyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ukey.SimpleRsaPublicKey)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Encoded in big-endian two's complement
   * </pre>
   *
   * <code>bytes n = 1;</code>
   * @return The n.
   */
  com.google.protobuf.ByteString getN();

  /**
   * <code>int32 e = 2;</code>
   * @return The e.
   */
  int getE();
}
