// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: events.proto

package com.textrcs.gmproto.events;

public interface EncryptedData2ContainerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:events.EncryptedData2Container)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.events.AccountChangeOrSomethingEvent accountChange = 2;</code>
   * @return Whether the accountChange field is set.
   */
  boolean hasAccountChange();
  /**
   * <code>.events.AccountChangeOrSomethingEvent accountChange = 2;</code>
   * @return The accountChange.
   */
  com.textrcs.gmproto.events.AccountChangeOrSomethingEvent getAccountChange();
  /**
   * <code>.events.AccountChangeOrSomethingEvent accountChange = 2;</code>
   */
  com.textrcs.gmproto.events.AccountChangeOrSomethingEventOrBuilder getAccountChangeOrBuilder();
}
