// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: events.proto

package com.textrcs.gmproto.events;

/**
 * Protobuf type {@code events.RPCPairData}
 */
public final class RPCPairData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:events.RPCPairData)
    RPCPairDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RPCPairData.newBuilder() to construct.
  private RPCPairData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RPCPairData() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RPCPairData();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.textrcs.gmproto.events.Events.internal_static_events_RPCPairData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.textrcs.gmproto.events.Events.internal_static_events_RPCPairData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.textrcs.gmproto.events.RPCPairData.class, com.textrcs.gmproto.events.RPCPairData.Builder.class);
  }

  private int eventCase_ = 0;
  private java.lang.Object event_;
  public enum EventCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    PAIRED(4),
    REVOKED(5),
    EVENT_NOT_SET(0);
    private final int value;
    private EventCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EventCase valueOf(int value) {
      return forNumber(value);
    }

    public static EventCase forNumber(int value) {
      switch (value) {
        case 4: return PAIRED;
        case 5: return REVOKED;
        case 0: return EVENT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public EventCase
  getEventCase() {
    return EventCase.forNumber(
        eventCase_);
  }

  public static final int PAIRED_FIELD_NUMBER = 4;
  /**
   * <code>.authentication.PairedData paired = 4;</code>
   * @return Whether the paired field is set.
   */
  @java.lang.Override
  public boolean hasPaired() {
    return eventCase_ == 4;
  }
  /**
   * <code>.authentication.PairedData paired = 4;</code>
   * @return The paired.
   */
  @java.lang.Override
  public com.textrcs.gmproto.authentication.PairedData getPaired() {
    if (eventCase_ == 4) {
       return (com.textrcs.gmproto.authentication.PairedData) event_;
    }
    return com.textrcs.gmproto.authentication.PairedData.getDefaultInstance();
  }
  /**
   * <code>.authentication.PairedData paired = 4;</code>
   */
  @java.lang.Override
  public com.textrcs.gmproto.authentication.PairedDataOrBuilder getPairedOrBuilder() {
    if (eventCase_ == 4) {
       return (com.textrcs.gmproto.authentication.PairedData) event_;
    }
    return com.textrcs.gmproto.authentication.PairedData.getDefaultInstance();
  }

  public static final int REVOKED_FIELD_NUMBER = 5;
  /**
   * <code>.authentication.RevokePairData revoked = 5;</code>
   * @return Whether the revoked field is set.
   */
  @java.lang.Override
  public boolean hasRevoked() {
    return eventCase_ == 5;
  }
  /**
   * <code>.authentication.RevokePairData revoked = 5;</code>
   * @return The revoked.
   */
  @java.lang.Override
  public com.textrcs.gmproto.authentication.RevokePairData getRevoked() {
    if (eventCase_ == 5) {
       return (com.textrcs.gmproto.authentication.RevokePairData) event_;
    }
    return com.textrcs.gmproto.authentication.RevokePairData.getDefaultInstance();
  }
  /**
   * <code>.authentication.RevokePairData revoked = 5;</code>
   */
  @java.lang.Override
  public com.textrcs.gmproto.authentication.RevokePairDataOrBuilder getRevokedOrBuilder() {
    if (eventCase_ == 5) {
       return (com.textrcs.gmproto.authentication.RevokePairData) event_;
    }
    return com.textrcs.gmproto.authentication.RevokePairData.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (eventCase_ == 4) {
      output.writeMessage(4, (com.textrcs.gmproto.authentication.PairedData) event_);
    }
    if (eventCase_ == 5) {
      output.writeMessage(5, (com.textrcs.gmproto.authentication.RevokePairData) event_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (eventCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (com.textrcs.gmproto.authentication.PairedData) event_);
    }
    if (eventCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (com.textrcs.gmproto.authentication.RevokePairData) event_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.textrcs.gmproto.events.RPCPairData)) {
      return super.equals(obj);
    }
    com.textrcs.gmproto.events.RPCPairData other = (com.textrcs.gmproto.events.RPCPairData) obj;

    if (!getEventCase().equals(other.getEventCase())) return false;
    switch (eventCase_) {
      case 4:
        if (!getPaired()
            .equals(other.getPaired())) return false;
        break;
      case 5:
        if (!getRevoked()
            .equals(other.getRevoked())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (eventCase_) {
      case 4:
        hash = (37 * hash) + PAIRED_FIELD_NUMBER;
        hash = (53 * hash) + getPaired().hashCode();
        break;
      case 5:
        hash = (37 * hash) + REVOKED_FIELD_NUMBER;
        hash = (53 * hash) + getRevoked().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.textrcs.gmproto.events.RPCPairData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.events.RPCPairData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.events.RPCPairData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.events.RPCPairData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.events.RPCPairData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.events.RPCPairData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.events.RPCPairData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.events.RPCPairData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.textrcs.gmproto.events.RPCPairData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.events.RPCPairData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.textrcs.gmproto.events.RPCPairData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.events.RPCPairData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.textrcs.gmproto.events.RPCPairData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code events.RPCPairData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:events.RPCPairData)
      com.textrcs.gmproto.events.RPCPairDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.textrcs.gmproto.events.Events.internal_static_events_RPCPairData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.textrcs.gmproto.events.Events.internal_static_events_RPCPairData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.textrcs.gmproto.events.RPCPairData.class, com.textrcs.gmproto.events.RPCPairData.Builder.class);
    }

    // Construct using com.textrcs.gmproto.events.RPCPairData.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (pairedBuilder_ != null) {
        pairedBuilder_.clear();
      }
      if (revokedBuilder_ != null) {
        revokedBuilder_.clear();
      }
      eventCase_ = 0;
      event_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.textrcs.gmproto.events.Events.internal_static_events_RPCPairData_descriptor;
    }

    @java.lang.Override
    public com.textrcs.gmproto.events.RPCPairData getDefaultInstanceForType() {
      return com.textrcs.gmproto.events.RPCPairData.getDefaultInstance();
    }

    @java.lang.Override
    public com.textrcs.gmproto.events.RPCPairData build() {
      com.textrcs.gmproto.events.RPCPairData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.textrcs.gmproto.events.RPCPairData buildPartial() {
      com.textrcs.gmproto.events.RPCPairData result = new com.textrcs.gmproto.events.RPCPairData(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.textrcs.gmproto.events.RPCPairData result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.textrcs.gmproto.events.RPCPairData result) {
      result.eventCase_ = eventCase_;
      result.event_ = this.event_;
      if (eventCase_ == 4 &&
          pairedBuilder_ != null) {
        result.event_ = pairedBuilder_.build();
      }
      if (eventCase_ == 5 &&
          revokedBuilder_ != null) {
        result.event_ = revokedBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.textrcs.gmproto.events.RPCPairData) {
        return mergeFrom((com.textrcs.gmproto.events.RPCPairData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.textrcs.gmproto.events.RPCPairData other) {
      if (other == com.textrcs.gmproto.events.RPCPairData.getDefaultInstance()) return this;
      switch (other.getEventCase()) {
        case PAIRED: {
          mergePaired(other.getPaired());
          break;
        }
        case REVOKED: {
          mergeRevoked(other.getRevoked());
          break;
        }
        case EVENT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 34: {
              input.readMessage(
                  getPairedFieldBuilder().getBuilder(),
                  extensionRegistry);
              eventCase_ = 4;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getRevokedFieldBuilder().getBuilder(),
                  extensionRegistry);
              eventCase_ = 5;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int eventCase_ = 0;
    private java.lang.Object event_;
    public EventCase
        getEventCase() {
      return EventCase.forNumber(
          eventCase_);
    }

    public Builder clearEvent() {
      eventCase_ = 0;
      event_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilderV3<
        com.textrcs.gmproto.authentication.PairedData, com.textrcs.gmproto.authentication.PairedData.Builder, com.textrcs.gmproto.authentication.PairedDataOrBuilder> pairedBuilder_;
    /**
     * <code>.authentication.PairedData paired = 4;</code>
     * @return Whether the paired field is set.
     */
    @java.lang.Override
    public boolean hasPaired() {
      return eventCase_ == 4;
    }
    /**
     * <code>.authentication.PairedData paired = 4;</code>
     * @return The paired.
     */
    @java.lang.Override
    public com.textrcs.gmproto.authentication.PairedData getPaired() {
      if (pairedBuilder_ == null) {
        if (eventCase_ == 4) {
          return (com.textrcs.gmproto.authentication.PairedData) event_;
        }
        return com.textrcs.gmproto.authentication.PairedData.getDefaultInstance();
      } else {
        if (eventCase_ == 4) {
          return pairedBuilder_.getMessage();
        }
        return com.textrcs.gmproto.authentication.PairedData.getDefaultInstance();
      }
    }
    /**
     * <code>.authentication.PairedData paired = 4;</code>
     */
    public Builder setPaired(com.textrcs.gmproto.authentication.PairedData value) {
      if (pairedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        pairedBuilder_.setMessage(value);
      }
      eventCase_ = 4;
      return this;
    }
    /**
     * <code>.authentication.PairedData paired = 4;</code>
     */
    public Builder setPaired(
        com.textrcs.gmproto.authentication.PairedData.Builder builderForValue) {
      if (pairedBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        pairedBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 4;
      return this;
    }
    /**
     * <code>.authentication.PairedData paired = 4;</code>
     */
    public Builder mergePaired(com.textrcs.gmproto.authentication.PairedData value) {
      if (pairedBuilder_ == null) {
        if (eventCase_ == 4 &&
            event_ != com.textrcs.gmproto.authentication.PairedData.getDefaultInstance()) {
          event_ = com.textrcs.gmproto.authentication.PairedData.newBuilder((com.textrcs.gmproto.authentication.PairedData) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 4) {
          pairedBuilder_.mergeFrom(value);
        } else {
          pairedBuilder_.setMessage(value);
        }
      }
      eventCase_ = 4;
      return this;
    }
    /**
     * <code>.authentication.PairedData paired = 4;</code>
     */
    public Builder clearPaired() {
      if (pairedBuilder_ == null) {
        if (eventCase_ == 4) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 4) {
          eventCase_ = 0;
          event_ = null;
        }
        pairedBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.authentication.PairedData paired = 4;</code>
     */
    public com.textrcs.gmproto.authentication.PairedData.Builder getPairedBuilder() {
      return getPairedFieldBuilder().getBuilder();
    }
    /**
     * <code>.authentication.PairedData paired = 4;</code>
     */
    @java.lang.Override
    public com.textrcs.gmproto.authentication.PairedDataOrBuilder getPairedOrBuilder() {
      if ((eventCase_ == 4) && (pairedBuilder_ != null)) {
        return pairedBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 4) {
          return (com.textrcs.gmproto.authentication.PairedData) event_;
        }
        return com.textrcs.gmproto.authentication.PairedData.getDefaultInstance();
      }
    }
    /**
     * <code>.authentication.PairedData paired = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.textrcs.gmproto.authentication.PairedData, com.textrcs.gmproto.authentication.PairedData.Builder, com.textrcs.gmproto.authentication.PairedDataOrBuilder> 
        getPairedFieldBuilder() {
      if (pairedBuilder_ == null) {
        if (!(eventCase_ == 4)) {
          event_ = com.textrcs.gmproto.authentication.PairedData.getDefaultInstance();
        }
        pairedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.textrcs.gmproto.authentication.PairedData, com.textrcs.gmproto.authentication.PairedData.Builder, com.textrcs.gmproto.authentication.PairedDataOrBuilder>(
                (com.textrcs.gmproto.authentication.PairedData) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 4;
      onChanged();
      return pairedBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.textrcs.gmproto.authentication.RevokePairData, com.textrcs.gmproto.authentication.RevokePairData.Builder, com.textrcs.gmproto.authentication.RevokePairDataOrBuilder> revokedBuilder_;
    /**
     * <code>.authentication.RevokePairData revoked = 5;</code>
     * @return Whether the revoked field is set.
     */
    @java.lang.Override
    public boolean hasRevoked() {
      return eventCase_ == 5;
    }
    /**
     * <code>.authentication.RevokePairData revoked = 5;</code>
     * @return The revoked.
     */
    @java.lang.Override
    public com.textrcs.gmproto.authentication.RevokePairData getRevoked() {
      if (revokedBuilder_ == null) {
        if (eventCase_ == 5) {
          return (com.textrcs.gmproto.authentication.RevokePairData) event_;
        }
        return com.textrcs.gmproto.authentication.RevokePairData.getDefaultInstance();
      } else {
        if (eventCase_ == 5) {
          return revokedBuilder_.getMessage();
        }
        return com.textrcs.gmproto.authentication.RevokePairData.getDefaultInstance();
      }
    }
    /**
     * <code>.authentication.RevokePairData revoked = 5;</code>
     */
    public Builder setRevoked(com.textrcs.gmproto.authentication.RevokePairData value) {
      if (revokedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        revokedBuilder_.setMessage(value);
      }
      eventCase_ = 5;
      return this;
    }
    /**
     * <code>.authentication.RevokePairData revoked = 5;</code>
     */
    public Builder setRevoked(
        com.textrcs.gmproto.authentication.RevokePairData.Builder builderForValue) {
      if (revokedBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        revokedBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 5;
      return this;
    }
    /**
     * <code>.authentication.RevokePairData revoked = 5;</code>
     */
    public Builder mergeRevoked(com.textrcs.gmproto.authentication.RevokePairData value) {
      if (revokedBuilder_ == null) {
        if (eventCase_ == 5 &&
            event_ != com.textrcs.gmproto.authentication.RevokePairData.getDefaultInstance()) {
          event_ = com.textrcs.gmproto.authentication.RevokePairData.newBuilder((com.textrcs.gmproto.authentication.RevokePairData) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 5) {
          revokedBuilder_.mergeFrom(value);
        } else {
          revokedBuilder_.setMessage(value);
        }
      }
      eventCase_ = 5;
      return this;
    }
    /**
     * <code>.authentication.RevokePairData revoked = 5;</code>
     */
    public Builder clearRevoked() {
      if (revokedBuilder_ == null) {
        if (eventCase_ == 5) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 5) {
          eventCase_ = 0;
          event_ = null;
        }
        revokedBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.authentication.RevokePairData revoked = 5;</code>
     */
    public com.textrcs.gmproto.authentication.RevokePairData.Builder getRevokedBuilder() {
      return getRevokedFieldBuilder().getBuilder();
    }
    /**
     * <code>.authentication.RevokePairData revoked = 5;</code>
     */
    @java.lang.Override
    public com.textrcs.gmproto.authentication.RevokePairDataOrBuilder getRevokedOrBuilder() {
      if ((eventCase_ == 5) && (revokedBuilder_ != null)) {
        return revokedBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 5) {
          return (com.textrcs.gmproto.authentication.RevokePairData) event_;
        }
        return com.textrcs.gmproto.authentication.RevokePairData.getDefaultInstance();
      }
    }
    /**
     * <code>.authentication.RevokePairData revoked = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.textrcs.gmproto.authentication.RevokePairData, com.textrcs.gmproto.authentication.RevokePairData.Builder, com.textrcs.gmproto.authentication.RevokePairDataOrBuilder> 
        getRevokedFieldBuilder() {
      if (revokedBuilder_ == null) {
        if (!(eventCase_ == 5)) {
          event_ = com.textrcs.gmproto.authentication.RevokePairData.getDefaultInstance();
        }
        revokedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.textrcs.gmproto.authentication.RevokePairData, com.textrcs.gmproto.authentication.RevokePairData.Builder, com.textrcs.gmproto.authentication.RevokePairDataOrBuilder>(
                (com.textrcs.gmproto.authentication.RevokePairData) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 5;
      onChanged();
      return revokedBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:events.RPCPairData)
  }

  // @@protoc_insertion_point(class_scope:events.RPCPairData)
  private static final com.textrcs.gmproto.events.RPCPairData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.textrcs.gmproto.events.RPCPairData();
  }

  public static com.textrcs.gmproto.events.RPCPairData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RPCPairData>
      PARSER = new com.google.protobuf.AbstractParser<RPCPairData>() {
    @java.lang.Override
    public RPCPairData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RPCPairData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RPCPairData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.textrcs.gmproto.events.RPCPairData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

