// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: events.proto

package com.textrcs.gmproto.events;

/**
 * Protobuf type {@code events.UserAlertEvent}
 */
public final class UserAlertEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:events.UserAlertEvent)
    UserAlertEventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserAlertEvent.newBuilder() to construct.
  private UserAlertEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserAlertEvent() {
    alertType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UserAlertEvent();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.textrcs.gmproto.events.Events.internal_static_events_UserAlertEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.textrcs.gmproto.events.Events.internal_static_events_UserAlertEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.textrcs.gmproto.events.UserAlertEvent.class, com.textrcs.gmproto.events.UserAlertEvent.Builder.class);
  }

  public static final int ALERTTYPE_FIELD_NUMBER = 2;
  private int alertType_ = 0;
  /**
   * <code>.events.AlertType alertType = 2;</code>
   * @return The enum numeric value on the wire for alertType.
   */
  @java.lang.Override public int getAlertTypeValue() {
    return alertType_;
  }
  /**
   * <code>.events.AlertType alertType = 2;</code>
   * @return The alertType.
   */
  @java.lang.Override public com.textrcs.gmproto.events.AlertType getAlertType() {
    com.textrcs.gmproto.events.AlertType result = com.textrcs.gmproto.events.AlertType.forNumber(alertType_);
    return result == null ? com.textrcs.gmproto.events.AlertType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (alertType_ != com.textrcs.gmproto.events.AlertType.ALERT_TYPE_UNKNOWN.getNumber()) {
      output.writeEnum(2, alertType_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (alertType_ != com.textrcs.gmproto.events.AlertType.ALERT_TYPE_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, alertType_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.textrcs.gmproto.events.UserAlertEvent)) {
      return super.equals(obj);
    }
    com.textrcs.gmproto.events.UserAlertEvent other = (com.textrcs.gmproto.events.UserAlertEvent) obj;

    if (alertType_ != other.alertType_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ALERTTYPE_FIELD_NUMBER;
    hash = (53 * hash) + alertType_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.textrcs.gmproto.events.UserAlertEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.events.UserAlertEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.events.UserAlertEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.events.UserAlertEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.events.UserAlertEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.events.UserAlertEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.events.UserAlertEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.events.UserAlertEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.textrcs.gmproto.events.UserAlertEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.events.UserAlertEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.textrcs.gmproto.events.UserAlertEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.events.UserAlertEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.textrcs.gmproto.events.UserAlertEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code events.UserAlertEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:events.UserAlertEvent)
      com.textrcs.gmproto.events.UserAlertEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.textrcs.gmproto.events.Events.internal_static_events_UserAlertEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.textrcs.gmproto.events.Events.internal_static_events_UserAlertEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.textrcs.gmproto.events.UserAlertEvent.class, com.textrcs.gmproto.events.UserAlertEvent.Builder.class);
    }

    // Construct using com.textrcs.gmproto.events.UserAlertEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      alertType_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.textrcs.gmproto.events.Events.internal_static_events_UserAlertEvent_descriptor;
    }

    @java.lang.Override
    public com.textrcs.gmproto.events.UserAlertEvent getDefaultInstanceForType() {
      return com.textrcs.gmproto.events.UserAlertEvent.getDefaultInstance();
    }

    @java.lang.Override
    public com.textrcs.gmproto.events.UserAlertEvent build() {
      com.textrcs.gmproto.events.UserAlertEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.textrcs.gmproto.events.UserAlertEvent buildPartial() {
      com.textrcs.gmproto.events.UserAlertEvent result = new com.textrcs.gmproto.events.UserAlertEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.textrcs.gmproto.events.UserAlertEvent result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.alertType_ = alertType_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.textrcs.gmproto.events.UserAlertEvent) {
        return mergeFrom((com.textrcs.gmproto.events.UserAlertEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.textrcs.gmproto.events.UserAlertEvent other) {
      if (other == com.textrcs.gmproto.events.UserAlertEvent.getDefaultInstance()) return this;
      if (other.alertType_ != 0) {
        setAlertTypeValue(other.getAlertTypeValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 16: {
              alertType_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int alertType_ = 0;
    /**
     * <code>.events.AlertType alertType = 2;</code>
     * @return The enum numeric value on the wire for alertType.
     */
    @java.lang.Override public int getAlertTypeValue() {
      return alertType_;
    }
    /**
     * <code>.events.AlertType alertType = 2;</code>
     * @param value The enum numeric value on the wire for alertType to set.
     * @return This builder for chaining.
     */
    public Builder setAlertTypeValue(int value) {
      alertType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.events.AlertType alertType = 2;</code>
     * @return The alertType.
     */
    @java.lang.Override
    public com.textrcs.gmproto.events.AlertType getAlertType() {
      com.textrcs.gmproto.events.AlertType result = com.textrcs.gmproto.events.AlertType.forNumber(alertType_);
      return result == null ? com.textrcs.gmproto.events.AlertType.UNRECOGNIZED : result;
    }
    /**
     * <code>.events.AlertType alertType = 2;</code>
     * @param value The alertType to set.
     * @return This builder for chaining.
     */
    public Builder setAlertType(com.textrcs.gmproto.events.AlertType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      alertType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.events.AlertType alertType = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAlertType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      alertType_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:events.UserAlertEvent)
  }

  // @@protoc_insertion_point(class_scope:events.UserAlertEvent)
  private static final com.textrcs.gmproto.events.UserAlertEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.textrcs.gmproto.events.UserAlertEvent();
  }

  public static com.textrcs.gmproto.events.UserAlertEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserAlertEvent>
      PARSER = new com.google.protobuf.AbstractParser<UserAlertEvent>() {
    @java.lang.Override
    public UserAlertEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UserAlertEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserAlertEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.textrcs.gmproto.events.UserAlertEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

