// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authentication.proto

package com.textrcs.gmproto.authentication;

public interface AuthenticationContainerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:authentication.AuthenticationContainer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.authentication.AuthMessage authMessage = 1;</code>
   * @return Whether the authMessage field is set.
   */
  boolean hasAuthMessage();
  /**
   * <code>.authentication.AuthMessage authMessage = 1;</code>
   * @return The authMessage.
   */
  com.textrcs.gmproto.authentication.AuthMessage getAuthMessage();
  /**
   * <code>.authentication.AuthMessage authMessage = 1;</code>
   */
  com.textrcs.gmproto.authentication.AuthMessageOrBuilder getAuthMessageOrBuilder();

  /**
   * <code>.authentication.BrowserDetails browserDetails = 3;</code>
   * @return Whether the browserDetails field is set.
   */
  boolean hasBrowserDetails();
  /**
   * <code>.authentication.BrowserDetails browserDetails = 3;</code>
   * @return The browserDetails.
   */
  com.textrcs.gmproto.authentication.BrowserDetails getBrowserDetails();
  /**
   * <code>.authentication.BrowserDetails browserDetails = 3;</code>
   */
  com.textrcs.gmproto.authentication.BrowserDetailsOrBuilder getBrowserDetailsOrBuilder();

  /**
   * <code>.authentication.KeyData keyData = 4;</code>
   * @return Whether the keyData field is set.
   */
  boolean hasKeyData();
  /**
   * <code>.authentication.KeyData keyData = 4;</code>
   * @return The keyData.
   */
  com.textrcs.gmproto.authentication.KeyData getKeyData();
  /**
   * <code>.authentication.KeyData keyData = 4;</code>
   */
  com.textrcs.gmproto.authentication.KeyDataOrBuilder getKeyDataOrBuilder();

  /**
   * <code>.authentication.CurrentDeviceData deviceData = 5;</code>
   * @return Whether the deviceData field is set.
   */
  boolean hasDeviceData();
  /**
   * <code>.authentication.CurrentDeviceData deviceData = 5;</code>
   * @return The deviceData.
   */
  com.textrcs.gmproto.authentication.CurrentDeviceData getDeviceData();
  /**
   * <code>.authentication.CurrentDeviceData deviceData = 5;</code>
   */
  com.textrcs.gmproto.authentication.CurrentDeviceDataOrBuilder getDeviceDataOrBuilder();

  public com.textrcs.gmproto.authentication.AuthenticationContainer.DataCase getDataCase();
}
