// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authentication.proto

package com.textrcs.gmproto.authentication;

/**
 * Protobuf enum {@code authentication.BrowserType}
 */
public enum BrowserType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN_BROWSER_TYPE = 0;</code>
   */
  UNKNOWN_BROWSER_TYPE(0),
  /**
   * <code>OTHER = 1;</code>
   */
  OTHER(1),
  /**
   * <code>CHROME = 2;</code>
   */
  CHROME(2),
  /**
   * <code>FIREFOX = 3;</code>
   */
  FIREFOX(3),
  /**
   * <code>SAFARI = 4;</code>
   */
  SAFARI(4),
  /**
   * <code>OPERA = 5;</code>
   */
  OPERA(5),
  /**
   * <code>IE = 6;</code>
   */
  IE(6),
  /**
   * <code>EDGE = 7;</code>
   */
  EDGE(7),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOWN_BROWSER_TYPE = 0;</code>
   */
  public static final int UNKNOWN_BROWSER_TYPE_VALUE = 0;
  /**
   * <code>OTHER = 1;</code>
   */
  public static final int OTHER_VALUE = 1;
  /**
   * <code>CHROME = 2;</code>
   */
  public static final int CHROME_VALUE = 2;
  /**
   * <code>FIREFOX = 3;</code>
   */
  public static final int FIREFOX_VALUE = 3;
  /**
   * <code>SAFARI = 4;</code>
   */
  public static final int SAFARI_VALUE = 4;
  /**
   * <code>OPERA = 5;</code>
   */
  public static final int OPERA_VALUE = 5;
  /**
   * <code>IE = 6;</code>
   */
  public static final int IE_VALUE = 6;
  /**
   * <code>EDGE = 7;</code>
   */
  public static final int EDGE_VALUE = 7;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static BrowserType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static BrowserType forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN_BROWSER_TYPE;
      case 1: return OTHER;
      case 2: return CHROME;
      case 3: return FIREFOX;
      case 4: return SAFARI;
      case 5: return OPERA;
      case 6: return IE;
      case 7: return EDGE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<BrowserType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      BrowserType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<BrowserType>() {
          public BrowserType findValueByNumber(int number) {
            return BrowserType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.textrcs.gmproto.authentication.Authentication.getDescriptor().getEnumTypes().get(0);
  }

  private static final BrowserType[] VALUES = values();

  public static BrowserType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private BrowserType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:authentication.BrowserType)
}

