// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authentication.proto

package com.textrcs.gmproto.authentication;

public interface CurrentDeviceDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:authentication.CurrentDeviceData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.authentication.Device browser = 1;</code>
   * @return Whether the browser field is set.
   */
  boolean hasBrowser();
  /**
   * <code>.authentication.Device browser = 1;</code>
   * @return The browser.
   */
  com.textrcs.gmproto.authentication.Device getBrowser();
  /**
   * <code>.authentication.Device browser = 1;</code>
   */
  com.textrcs.gmproto.authentication.DeviceOrBuilder getBrowserOrBuilder();
}
