// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authentication.proto

package com.textrcs.gmproto.authentication;

public interface ErrorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:authentication.ErrorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 5?
   * </pre>
   *
   * <code>int64 type = 1;</code>
   * @return The type.
   */
  long getType();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>repeated .authentication.ErrorResponse.ErrorClass class = 3;</code>
   */
  java.util.List<com.textrcs.gmproto.authentication.ErrorResponse.ErrorClass> 
      getClass_List();
  /**
   * <code>repeated .authentication.ErrorResponse.ErrorClass class = 3;</code>
   */
  com.textrcs.gmproto.authentication.ErrorResponse.ErrorClass getClass_(int index);
  /**
   * <code>repeated .authentication.ErrorResponse.ErrorClass class = 3;</code>
   */
  int getClass_Count();
  /**
   * <code>repeated .authentication.ErrorResponse.ErrorClass class = 3;</code>
   */
  java.util.List<? extends com.textrcs.gmproto.authentication.ErrorResponse.ErrorClassOrBuilder> 
      getClass_OrBuilderList();
  /**
   * <code>repeated .authentication.ErrorResponse.ErrorClass class = 3;</code>
   */
  com.textrcs.gmproto.authentication.ErrorResponse.ErrorClassOrBuilder getClass_OrBuilder(
      int index);
}
