// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authentication.proto

package com.textrcs.gmproto.authentication;

public interface RegisterRefreshResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:authentication.RegisterRefreshResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.authentication.TokenData tokenData = 2;</code>
   * @return Whether the tokenData field is set.
   */
  boolean hasTokenData();
  /**
   * <code>.authentication.TokenData tokenData = 2;</code>
   * @return The tokenData.
   */
  com.textrcs.gmproto.authentication.TokenData getTokenData();
  /**
   * <code>.authentication.TokenData tokenData = 2;</code>
   */
  com.textrcs.gmproto.authentication.TokenDataOrBuilder getTokenDataOrBuilder();
}
