// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authentication.proto

package com.textrcs.gmproto.authentication;

public interface URLDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:authentication.URLData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes pairingKey = 1;</code>
   * @return The pairingKey.
   */
  com.google.protobuf.ByteString getPairingKey();

  /**
   * <code>bytes AESKey = 2;</code>
   * @return The aESKey.
   */
  com.google.protobuf.ByteString getAESKey();

  /**
   * <code>bytes HMACKey = 3;</code>
   * @return The hMACKey.
   */
  com.google.protobuf.ByteString getHMACKey();
}
