// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package com.textrcs.gmproto.client;

/**
 * Protobuf type {@code client.AttachmentInfo}
 */
public final class AttachmentInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:client.AttachmentInfo)
    AttachmentInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AttachmentInfo.newBuilder() to construct.
  private AttachmentInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AttachmentInfo() {
    attachmentID_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AttachmentInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.textrcs.gmproto.client.Client.internal_static_client_AttachmentInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.textrcs.gmproto.client.Client.internal_static_client_AttachmentInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.textrcs.gmproto.client.AttachmentInfo.class, com.textrcs.gmproto.client.AttachmentInfo.Builder.class);
  }

  public static final int ATTACHMENTID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object attachmentID_ = "";
  /**
   * <code>string attachmentID = 1;</code>
   * @return The attachmentID.
   */
  @java.lang.Override
  public java.lang.String getAttachmentID() {
    java.lang.Object ref = attachmentID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      attachmentID_ = s;
      return s;
    }
  }
  /**
   * <code>string attachmentID = 1;</code>
   * @return The bytes for attachmentID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAttachmentIDBytes() {
    java.lang.Object ref = attachmentID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      attachmentID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENCRYPTED_FIELD_NUMBER = 2;
  private boolean encrypted_ = false;
  /**
   * <code>bool encrypted = 2;</code>
   * @return The encrypted.
   */
  @java.lang.Override
  public boolean getEncrypted() {
    return encrypted_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(attachmentID_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, attachmentID_);
    }
    if (encrypted_ != false) {
      output.writeBool(2, encrypted_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(attachmentID_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, attachmentID_);
    }
    if (encrypted_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, encrypted_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.textrcs.gmproto.client.AttachmentInfo)) {
      return super.equals(obj);
    }
    com.textrcs.gmproto.client.AttachmentInfo other = (com.textrcs.gmproto.client.AttachmentInfo) obj;

    if (!getAttachmentID()
        .equals(other.getAttachmentID())) return false;
    if (getEncrypted()
        != other.getEncrypted()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ATTACHMENTID_FIELD_NUMBER;
    hash = (53 * hash) + getAttachmentID().hashCode();
    hash = (37 * hash) + ENCRYPTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getEncrypted());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.textrcs.gmproto.client.AttachmentInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.client.AttachmentInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.client.AttachmentInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.client.AttachmentInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.client.AttachmentInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.client.AttachmentInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.client.AttachmentInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.client.AttachmentInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.textrcs.gmproto.client.AttachmentInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.client.AttachmentInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.textrcs.gmproto.client.AttachmentInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.client.AttachmentInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.textrcs.gmproto.client.AttachmentInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code client.AttachmentInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:client.AttachmentInfo)
      com.textrcs.gmproto.client.AttachmentInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.textrcs.gmproto.client.Client.internal_static_client_AttachmentInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.textrcs.gmproto.client.Client.internal_static_client_AttachmentInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.textrcs.gmproto.client.AttachmentInfo.class, com.textrcs.gmproto.client.AttachmentInfo.Builder.class);
    }

    // Construct using com.textrcs.gmproto.client.AttachmentInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      attachmentID_ = "";
      encrypted_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.textrcs.gmproto.client.Client.internal_static_client_AttachmentInfo_descriptor;
    }

    @java.lang.Override
    public com.textrcs.gmproto.client.AttachmentInfo getDefaultInstanceForType() {
      return com.textrcs.gmproto.client.AttachmentInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.textrcs.gmproto.client.AttachmentInfo build() {
      com.textrcs.gmproto.client.AttachmentInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.textrcs.gmproto.client.AttachmentInfo buildPartial() {
      com.textrcs.gmproto.client.AttachmentInfo result = new com.textrcs.gmproto.client.AttachmentInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.textrcs.gmproto.client.AttachmentInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.attachmentID_ = attachmentID_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.encrypted_ = encrypted_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.textrcs.gmproto.client.AttachmentInfo) {
        return mergeFrom((com.textrcs.gmproto.client.AttachmentInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.textrcs.gmproto.client.AttachmentInfo other) {
      if (other == com.textrcs.gmproto.client.AttachmentInfo.getDefaultInstance()) return this;
      if (!other.getAttachmentID().isEmpty()) {
        attachmentID_ = other.attachmentID_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getEncrypted() != false) {
        setEncrypted(other.getEncrypted());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              attachmentID_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              encrypted_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object attachmentID_ = "";
    /**
     * <code>string attachmentID = 1;</code>
     * @return The attachmentID.
     */
    public java.lang.String getAttachmentID() {
      java.lang.Object ref = attachmentID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        attachmentID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string attachmentID = 1;</code>
     * @return The bytes for attachmentID.
     */
    public com.google.protobuf.ByteString
        getAttachmentIDBytes() {
      java.lang.Object ref = attachmentID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        attachmentID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string attachmentID = 1;</code>
     * @param value The attachmentID to set.
     * @return This builder for chaining.
     */
    public Builder setAttachmentID(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      attachmentID_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string attachmentID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAttachmentID() {
      attachmentID_ = getDefaultInstance().getAttachmentID();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string attachmentID = 1;</code>
     * @param value The bytes for attachmentID to set.
     * @return This builder for chaining.
     */
    public Builder setAttachmentIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      attachmentID_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private boolean encrypted_ ;
    /**
     * <code>bool encrypted = 2;</code>
     * @return The encrypted.
     */
    @java.lang.Override
    public boolean getEncrypted() {
      return encrypted_;
    }
    /**
     * <code>bool encrypted = 2;</code>
     * @param value The encrypted to set.
     * @return This builder for chaining.
     */
    public Builder setEncrypted(boolean value) {
      
      encrypted_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool encrypted = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEncrypted() {
      bitField0_ = (bitField0_ & ~0x00000002);
      encrypted_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:client.AttachmentInfo)
  }

  // @@protoc_insertion_point(class_scope:client.AttachmentInfo)
  private static final com.textrcs.gmproto.client.AttachmentInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.textrcs.gmproto.client.AttachmentInfo();
  }

  public static com.textrcs.gmproto.client.AttachmentInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AttachmentInfo>
      PARSER = new com.google.protobuf.AbstractParser<AttachmentInfo>() {
    @java.lang.Override
    public AttachmentInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AttachmentInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AttachmentInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.textrcs.gmproto.client.AttachmentInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

