// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package com.textrcs.gmproto.client;

public interface DownloadAttachmentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client.DownloadAttachmentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.client.AttachmentInfo info = 1;</code>
   * @return Whether the info field is set.
   */
  boolean hasInfo();
  /**
   * <code>.client.AttachmentInfo info = 1;</code>
   * @return The info.
   */
  com.textrcs.gmproto.client.AttachmentInfo getInfo();
  /**
   * <code>.client.AttachmentInfo info = 1;</code>
   */
  com.textrcs.gmproto.client.AttachmentInfoOrBuilder getInfoOrBuilder();

  /**
   * <code>.authentication.AuthMessage authData = 2;</code>
   * @return Whether the authData field is set.
   */
  boolean hasAuthData();
  /**
   * <code>.authentication.AuthMessage authData = 2;</code>
   * @return The authData.
   */
  com.textrcs.gmproto.authentication.AuthMessage getAuthData();
  /**
   * <code>.authentication.AuthMessage authData = 2;</code>
   */
  com.textrcs.gmproto.authentication.AuthMessageOrBuilder getAuthDataOrBuilder();
}
