// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package com.textrcs.gmproto.client;

public interface GetOrCreateConversationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:client.GetOrCreateConversationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.conversations.Conversation conversation = 2;</code>
   * @return Whether the conversation field is set.
   */
  boolean hasConversation();
  /**
   * <code>.conversations.Conversation conversation = 2;</code>
   * @return The conversation.
   */
  com.textrcs.gmproto.conversations.Conversation getConversation();
  /**
   * <code>.conversations.Conversation conversation = 2;</code>
   */
  com.textrcs.gmproto.conversations.ConversationOrBuilder getConversationOrBuilder();

  /**
   * <code>.client.GetOrCreateConversationResponse.Status status = 3;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.client.GetOrCreateConversationResponse.Status status = 3;</code>
   * @return The status.
   */
  com.textrcs.gmproto.client.GetOrCreateConversationResponse.Status getStatus();
}
