// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package com.textrcs.gmproto.client;

/**
 * Protobuf type {@code client.UpdateConversationRequest}
 */
public final class UpdateConversationRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:client.UpdateConversationRequest)
    UpdateConversationRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdateConversationRequest.newBuilder() to construct.
  private UpdateConversationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateConversationRequest() {
    action_ = 0;
    conversationID_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UpdateConversationRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.textrcs.gmproto.client.Client.internal_static_client_UpdateConversationRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.textrcs.gmproto.client.Client.internal_static_client_UpdateConversationRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.textrcs.gmproto.client.UpdateConversationRequest.class, com.textrcs.gmproto.client.UpdateConversationRequest.Builder.class);
  }

  private int bitField0_;
  private int dataCase_ = 0;
  private java.lang.Object data_;
  public enum DataCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    DELETEDATA(6),
    UPDATEDATA(1),
    DATA_NOT_SET(0);
    private final int value;
    private DataCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DataCase valueOf(int value) {
      return forNumber(value);
    }

    public static DataCase forNumber(int value) {
      switch (value) {
        case 6: return DELETEDATA;
        case 1: return UPDATEDATA;
        case 0: return DATA_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public DataCase
  getDataCase() {
    return DataCase.forNumber(
        dataCase_);
  }

  public static final int ACTION_FIELD_NUMBER = 2;
  private int action_ = 0;
  /**
   * <code>.client.ConversationActionStatus action = 2;</code>
   * @return The enum numeric value on the wire for action.
   */
  @java.lang.Override public int getActionValue() {
    return action_;
  }
  /**
   * <code>.client.ConversationActionStatus action = 2;</code>
   * @return The action.
   */
  @java.lang.Override public com.textrcs.gmproto.client.ConversationActionStatus getAction() {
    com.textrcs.gmproto.client.ConversationActionStatus result = com.textrcs.gmproto.client.ConversationActionStatus.forNumber(action_);
    return result == null ? com.textrcs.gmproto.client.ConversationActionStatus.UNRECOGNIZED : result;
  }

  public static final int CONVERSATIONID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object conversationID_ = "";
  /**
   * <code>string conversationID = 3;</code>
   * @return The conversationID.
   */
  @java.lang.Override
  public java.lang.String getConversationID() {
    java.lang.Object ref = conversationID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      conversationID_ = s;
      return s;
    }
  }
  /**
   * <code>string conversationID = 3;</code>
   * @return The bytes for conversationID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConversationIDBytes() {
    java.lang.Object ref = conversationID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      conversationID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACTION5_FIELD_NUMBER = 5;
  private com.textrcs.gmproto.client.ConversationAction5 action5_;
  /**
   * <code>optional .client.ConversationAction5 action5 = 5;</code>
   * @return Whether the action5 field is set.
   */
  @java.lang.Override
  public boolean hasAction5() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .client.ConversationAction5 action5 = 5;</code>
   * @return The action5.
   */
  @java.lang.Override
  public com.textrcs.gmproto.client.ConversationAction5 getAction5() {
    return action5_ == null ? com.textrcs.gmproto.client.ConversationAction5.getDefaultInstance() : action5_;
  }
  /**
   * <code>optional .client.ConversationAction5 action5 = 5;</code>
   */
  @java.lang.Override
  public com.textrcs.gmproto.client.ConversationAction5OrBuilder getAction5OrBuilder() {
    return action5_ == null ? com.textrcs.gmproto.client.ConversationAction5.getDefaultInstance() : action5_;
  }

  public static final int DELETEDATA_FIELD_NUMBER = 6;
  /**
   * <code>.client.DeleteConversationData deleteData = 6;</code>
   * @return Whether the deleteData field is set.
   */
  @java.lang.Override
  public boolean hasDeleteData() {
    return dataCase_ == 6;
  }
  /**
   * <code>.client.DeleteConversationData deleteData = 6;</code>
   * @return The deleteData.
   */
  @java.lang.Override
  public com.textrcs.gmproto.client.DeleteConversationData getDeleteData() {
    if (dataCase_ == 6) {
       return (com.textrcs.gmproto.client.DeleteConversationData) data_;
    }
    return com.textrcs.gmproto.client.DeleteConversationData.getDefaultInstance();
  }
  /**
   * <code>.client.DeleteConversationData deleteData = 6;</code>
   */
  @java.lang.Override
  public com.textrcs.gmproto.client.DeleteConversationDataOrBuilder getDeleteDataOrBuilder() {
    if (dataCase_ == 6) {
       return (com.textrcs.gmproto.client.DeleteConversationData) data_;
    }
    return com.textrcs.gmproto.client.DeleteConversationData.getDefaultInstance();
  }

  public static final int UPDATEDATA_FIELD_NUMBER = 1;
  /**
   * <code>.client.UpdateConversationData updateData = 1;</code>
   * @return Whether the updateData field is set.
   */
  @java.lang.Override
  public boolean hasUpdateData() {
    return dataCase_ == 1;
  }
  /**
   * <code>.client.UpdateConversationData updateData = 1;</code>
   * @return The updateData.
   */
  @java.lang.Override
  public com.textrcs.gmproto.client.UpdateConversationData getUpdateData() {
    if (dataCase_ == 1) {
       return (com.textrcs.gmproto.client.UpdateConversationData) data_;
    }
    return com.textrcs.gmproto.client.UpdateConversationData.getDefaultInstance();
  }
  /**
   * <code>.client.UpdateConversationData updateData = 1;</code>
   */
  @java.lang.Override
  public com.textrcs.gmproto.client.UpdateConversationDataOrBuilder getUpdateDataOrBuilder() {
    if (dataCase_ == 1) {
       return (com.textrcs.gmproto.client.UpdateConversationData) data_;
    }
    return com.textrcs.gmproto.client.UpdateConversationData.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (dataCase_ == 1) {
      output.writeMessage(1, (com.textrcs.gmproto.client.UpdateConversationData) data_);
    }
    if (action_ != com.textrcs.gmproto.client.ConversationActionStatus.UNKNOWN_ACTION_STATUS.getNumber()) {
      output.writeEnum(2, action_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(conversationID_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, conversationID_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(5, getAction5());
    }
    if (dataCase_ == 6) {
      output.writeMessage(6, (com.textrcs.gmproto.client.DeleteConversationData) data_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (dataCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.textrcs.gmproto.client.UpdateConversationData) data_);
    }
    if (action_ != com.textrcs.gmproto.client.ConversationActionStatus.UNKNOWN_ACTION_STATUS.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, action_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(conversationID_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, conversationID_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getAction5());
    }
    if (dataCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (com.textrcs.gmproto.client.DeleteConversationData) data_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.textrcs.gmproto.client.UpdateConversationRequest)) {
      return super.equals(obj);
    }
    com.textrcs.gmproto.client.UpdateConversationRequest other = (com.textrcs.gmproto.client.UpdateConversationRequest) obj;

    if (action_ != other.action_) return false;
    if (!getConversationID()
        .equals(other.getConversationID())) return false;
    if (hasAction5() != other.hasAction5()) return false;
    if (hasAction5()) {
      if (!getAction5()
          .equals(other.getAction5())) return false;
    }
    if (!getDataCase().equals(other.getDataCase())) return false;
    switch (dataCase_) {
      case 6:
        if (!getDeleteData()
            .equals(other.getDeleteData())) return false;
        break;
      case 1:
        if (!getUpdateData()
            .equals(other.getUpdateData())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACTION_FIELD_NUMBER;
    hash = (53 * hash) + action_;
    hash = (37 * hash) + CONVERSATIONID_FIELD_NUMBER;
    hash = (53 * hash) + getConversationID().hashCode();
    if (hasAction5()) {
      hash = (37 * hash) + ACTION5_FIELD_NUMBER;
      hash = (53 * hash) + getAction5().hashCode();
    }
    switch (dataCase_) {
      case 6:
        hash = (37 * hash) + DELETEDATA_FIELD_NUMBER;
        hash = (53 * hash) + getDeleteData().hashCode();
        break;
      case 1:
        hash = (37 * hash) + UPDATEDATA_FIELD_NUMBER;
        hash = (53 * hash) + getUpdateData().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.textrcs.gmproto.client.UpdateConversationRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.client.UpdateConversationRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.client.UpdateConversationRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.client.UpdateConversationRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.client.UpdateConversationRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.client.UpdateConversationRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.client.UpdateConversationRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.client.UpdateConversationRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.textrcs.gmproto.client.UpdateConversationRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.client.UpdateConversationRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.textrcs.gmproto.client.UpdateConversationRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.client.UpdateConversationRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.textrcs.gmproto.client.UpdateConversationRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code client.UpdateConversationRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:client.UpdateConversationRequest)
      com.textrcs.gmproto.client.UpdateConversationRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.textrcs.gmproto.client.Client.internal_static_client_UpdateConversationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.textrcs.gmproto.client.Client.internal_static_client_UpdateConversationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.textrcs.gmproto.client.UpdateConversationRequest.class, com.textrcs.gmproto.client.UpdateConversationRequest.Builder.class);
    }

    // Construct using com.textrcs.gmproto.client.UpdateConversationRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAction5FieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      action_ = 0;
      conversationID_ = "";
      action5_ = null;
      if (action5Builder_ != null) {
        action5Builder_.dispose();
        action5Builder_ = null;
      }
      if (deleteDataBuilder_ != null) {
        deleteDataBuilder_.clear();
      }
      if (updateDataBuilder_ != null) {
        updateDataBuilder_.clear();
      }
      dataCase_ = 0;
      data_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.textrcs.gmproto.client.Client.internal_static_client_UpdateConversationRequest_descriptor;
    }

    @java.lang.Override
    public com.textrcs.gmproto.client.UpdateConversationRequest getDefaultInstanceForType() {
      return com.textrcs.gmproto.client.UpdateConversationRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.textrcs.gmproto.client.UpdateConversationRequest build() {
      com.textrcs.gmproto.client.UpdateConversationRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.textrcs.gmproto.client.UpdateConversationRequest buildPartial() {
      com.textrcs.gmproto.client.UpdateConversationRequest result = new com.textrcs.gmproto.client.UpdateConversationRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.textrcs.gmproto.client.UpdateConversationRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.action_ = action_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.conversationID_ = conversationID_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.action5_ = action5Builder_ == null
            ? action5_
            : action5Builder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    private void buildPartialOneofs(com.textrcs.gmproto.client.UpdateConversationRequest result) {
      result.dataCase_ = dataCase_;
      result.data_ = this.data_;
      if (dataCase_ == 6 &&
          deleteDataBuilder_ != null) {
        result.data_ = deleteDataBuilder_.build();
      }
      if (dataCase_ == 1 &&
          updateDataBuilder_ != null) {
        result.data_ = updateDataBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.textrcs.gmproto.client.UpdateConversationRequest) {
        return mergeFrom((com.textrcs.gmproto.client.UpdateConversationRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.textrcs.gmproto.client.UpdateConversationRequest other) {
      if (other == com.textrcs.gmproto.client.UpdateConversationRequest.getDefaultInstance()) return this;
      if (other.action_ != 0) {
        setActionValue(other.getActionValue());
      }
      if (!other.getConversationID().isEmpty()) {
        conversationID_ = other.conversationID_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasAction5()) {
        mergeAction5(other.getAction5());
      }
      switch (other.getDataCase()) {
        case DELETEDATA: {
          mergeDeleteData(other.getDeleteData());
          break;
        }
        case UPDATEDATA: {
          mergeUpdateData(other.getUpdateData());
          break;
        }
        case DATA_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getUpdateDataFieldBuilder().getBuilder(),
                  extensionRegistry);
              dataCase_ = 1;
              break;
            } // case 10
            case 16: {
              action_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 16
            case 26: {
              conversationID_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 26
            case 42: {
              input.readMessage(
                  getAction5FieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getDeleteDataFieldBuilder().getBuilder(),
                  extensionRegistry);
              dataCase_ = 6;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int dataCase_ = 0;
    private java.lang.Object data_;
    public DataCase
        getDataCase() {
      return DataCase.forNumber(
          dataCase_);
    }

    public Builder clearData() {
      dataCase_ = 0;
      data_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private int action_ = 0;
    /**
     * <code>.client.ConversationActionStatus action = 2;</code>
     * @return The enum numeric value on the wire for action.
     */
    @java.lang.Override public int getActionValue() {
      return action_;
    }
    /**
     * <code>.client.ConversationActionStatus action = 2;</code>
     * @param value The enum numeric value on the wire for action to set.
     * @return This builder for chaining.
     */
    public Builder setActionValue(int value) {
      action_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.client.ConversationActionStatus action = 2;</code>
     * @return The action.
     */
    @java.lang.Override
    public com.textrcs.gmproto.client.ConversationActionStatus getAction() {
      com.textrcs.gmproto.client.ConversationActionStatus result = com.textrcs.gmproto.client.ConversationActionStatus.forNumber(action_);
      return result == null ? com.textrcs.gmproto.client.ConversationActionStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.client.ConversationActionStatus action = 2;</code>
     * @param value The action to set.
     * @return This builder for chaining.
     */
    public Builder setAction(com.textrcs.gmproto.client.ConversationActionStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      action_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.client.ConversationActionStatus action = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAction() {
      bitField0_ = (bitField0_ & ~0x00000001);
      action_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object conversationID_ = "";
    /**
     * <code>string conversationID = 3;</code>
     * @return The conversationID.
     */
    public java.lang.String getConversationID() {
      java.lang.Object ref = conversationID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        conversationID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string conversationID = 3;</code>
     * @return The bytes for conversationID.
     */
    public com.google.protobuf.ByteString
        getConversationIDBytes() {
      java.lang.Object ref = conversationID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        conversationID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string conversationID = 3;</code>
     * @param value The conversationID to set.
     * @return This builder for chaining.
     */
    public Builder setConversationID(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      conversationID_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string conversationID = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearConversationID() {
      conversationID_ = getDefaultInstance().getConversationID();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string conversationID = 3;</code>
     * @param value The bytes for conversationID to set.
     * @return This builder for chaining.
     */
    public Builder setConversationIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      conversationID_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.textrcs.gmproto.client.ConversationAction5 action5_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.textrcs.gmproto.client.ConversationAction5, com.textrcs.gmproto.client.ConversationAction5.Builder, com.textrcs.gmproto.client.ConversationAction5OrBuilder> action5Builder_;
    /**
     * <code>optional .client.ConversationAction5 action5 = 5;</code>
     * @return Whether the action5 field is set.
     */
    public boolean hasAction5() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .client.ConversationAction5 action5 = 5;</code>
     * @return The action5.
     */
    public com.textrcs.gmproto.client.ConversationAction5 getAction5() {
      if (action5Builder_ == null) {
        return action5_ == null ? com.textrcs.gmproto.client.ConversationAction5.getDefaultInstance() : action5_;
      } else {
        return action5Builder_.getMessage();
      }
    }
    /**
     * <code>optional .client.ConversationAction5 action5 = 5;</code>
     */
    public Builder setAction5(com.textrcs.gmproto.client.ConversationAction5 value) {
      if (action5Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        action5_ = value;
      } else {
        action5Builder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional .client.ConversationAction5 action5 = 5;</code>
     */
    public Builder setAction5(
        com.textrcs.gmproto.client.ConversationAction5.Builder builderForValue) {
      if (action5Builder_ == null) {
        action5_ = builderForValue.build();
      } else {
        action5Builder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional .client.ConversationAction5 action5 = 5;</code>
     */
    public Builder mergeAction5(com.textrcs.gmproto.client.ConversationAction5 value) {
      if (action5Builder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          action5_ != null &&
          action5_ != com.textrcs.gmproto.client.ConversationAction5.getDefaultInstance()) {
          getAction5Builder().mergeFrom(value);
        } else {
          action5_ = value;
        }
      } else {
        action5Builder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional .client.ConversationAction5 action5 = 5;</code>
     */
    public Builder clearAction5() {
      bitField0_ = (bitField0_ & ~0x00000004);
      action5_ = null;
      if (action5Builder_ != null) {
        action5Builder_.dispose();
        action5Builder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .client.ConversationAction5 action5 = 5;</code>
     */
    public com.textrcs.gmproto.client.ConversationAction5.Builder getAction5Builder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getAction5FieldBuilder().getBuilder();
    }
    /**
     * <code>optional .client.ConversationAction5 action5 = 5;</code>
     */
    public com.textrcs.gmproto.client.ConversationAction5OrBuilder getAction5OrBuilder() {
      if (action5Builder_ != null) {
        return action5Builder_.getMessageOrBuilder();
      } else {
        return action5_ == null ?
            com.textrcs.gmproto.client.ConversationAction5.getDefaultInstance() : action5_;
      }
    }
    /**
     * <code>optional .client.ConversationAction5 action5 = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.textrcs.gmproto.client.ConversationAction5, com.textrcs.gmproto.client.ConversationAction5.Builder, com.textrcs.gmproto.client.ConversationAction5OrBuilder> 
        getAction5FieldBuilder() {
      if (action5Builder_ == null) {
        action5Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.textrcs.gmproto.client.ConversationAction5, com.textrcs.gmproto.client.ConversationAction5.Builder, com.textrcs.gmproto.client.ConversationAction5OrBuilder>(
                getAction5(),
                getParentForChildren(),
                isClean());
        action5_ = null;
      }
      return action5Builder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.textrcs.gmproto.client.DeleteConversationData, com.textrcs.gmproto.client.DeleteConversationData.Builder, com.textrcs.gmproto.client.DeleteConversationDataOrBuilder> deleteDataBuilder_;
    /**
     * <code>.client.DeleteConversationData deleteData = 6;</code>
     * @return Whether the deleteData field is set.
     */
    @java.lang.Override
    public boolean hasDeleteData() {
      return dataCase_ == 6;
    }
    /**
     * <code>.client.DeleteConversationData deleteData = 6;</code>
     * @return The deleteData.
     */
    @java.lang.Override
    public com.textrcs.gmproto.client.DeleteConversationData getDeleteData() {
      if (deleteDataBuilder_ == null) {
        if (dataCase_ == 6) {
          return (com.textrcs.gmproto.client.DeleteConversationData) data_;
        }
        return com.textrcs.gmproto.client.DeleteConversationData.getDefaultInstance();
      } else {
        if (dataCase_ == 6) {
          return deleteDataBuilder_.getMessage();
        }
        return com.textrcs.gmproto.client.DeleteConversationData.getDefaultInstance();
      }
    }
    /**
     * <code>.client.DeleteConversationData deleteData = 6;</code>
     */
    public Builder setDeleteData(com.textrcs.gmproto.client.DeleteConversationData value) {
      if (deleteDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        deleteDataBuilder_.setMessage(value);
      }
      dataCase_ = 6;
      return this;
    }
    /**
     * <code>.client.DeleteConversationData deleteData = 6;</code>
     */
    public Builder setDeleteData(
        com.textrcs.gmproto.client.DeleteConversationData.Builder builderForValue) {
      if (deleteDataBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        deleteDataBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 6;
      return this;
    }
    /**
     * <code>.client.DeleteConversationData deleteData = 6;</code>
     */
    public Builder mergeDeleteData(com.textrcs.gmproto.client.DeleteConversationData value) {
      if (deleteDataBuilder_ == null) {
        if (dataCase_ == 6 &&
            data_ != com.textrcs.gmproto.client.DeleteConversationData.getDefaultInstance()) {
          data_ = com.textrcs.gmproto.client.DeleteConversationData.newBuilder((com.textrcs.gmproto.client.DeleteConversationData) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 6) {
          deleteDataBuilder_.mergeFrom(value);
        } else {
          deleteDataBuilder_.setMessage(value);
        }
      }
      dataCase_ = 6;
      return this;
    }
    /**
     * <code>.client.DeleteConversationData deleteData = 6;</code>
     */
    public Builder clearDeleteData() {
      if (deleteDataBuilder_ == null) {
        if (dataCase_ == 6) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 6) {
          dataCase_ = 0;
          data_ = null;
        }
        deleteDataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.client.DeleteConversationData deleteData = 6;</code>
     */
    public com.textrcs.gmproto.client.DeleteConversationData.Builder getDeleteDataBuilder() {
      return getDeleteDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.client.DeleteConversationData deleteData = 6;</code>
     */
    @java.lang.Override
    public com.textrcs.gmproto.client.DeleteConversationDataOrBuilder getDeleteDataOrBuilder() {
      if ((dataCase_ == 6) && (deleteDataBuilder_ != null)) {
        return deleteDataBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 6) {
          return (com.textrcs.gmproto.client.DeleteConversationData) data_;
        }
        return com.textrcs.gmproto.client.DeleteConversationData.getDefaultInstance();
      }
    }
    /**
     * <code>.client.DeleteConversationData deleteData = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.textrcs.gmproto.client.DeleteConversationData, com.textrcs.gmproto.client.DeleteConversationData.Builder, com.textrcs.gmproto.client.DeleteConversationDataOrBuilder> 
        getDeleteDataFieldBuilder() {
      if (deleteDataBuilder_ == null) {
        if (!(dataCase_ == 6)) {
          data_ = com.textrcs.gmproto.client.DeleteConversationData.getDefaultInstance();
        }
        deleteDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.textrcs.gmproto.client.DeleteConversationData, com.textrcs.gmproto.client.DeleteConversationData.Builder, com.textrcs.gmproto.client.DeleteConversationDataOrBuilder>(
                (com.textrcs.gmproto.client.DeleteConversationData) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 6;
      onChanged();
      return deleteDataBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.textrcs.gmproto.client.UpdateConversationData, com.textrcs.gmproto.client.UpdateConversationData.Builder, com.textrcs.gmproto.client.UpdateConversationDataOrBuilder> updateDataBuilder_;
    /**
     * <code>.client.UpdateConversationData updateData = 1;</code>
     * @return Whether the updateData field is set.
     */
    @java.lang.Override
    public boolean hasUpdateData() {
      return dataCase_ == 1;
    }
    /**
     * <code>.client.UpdateConversationData updateData = 1;</code>
     * @return The updateData.
     */
    @java.lang.Override
    public com.textrcs.gmproto.client.UpdateConversationData getUpdateData() {
      if (updateDataBuilder_ == null) {
        if (dataCase_ == 1) {
          return (com.textrcs.gmproto.client.UpdateConversationData) data_;
        }
        return com.textrcs.gmproto.client.UpdateConversationData.getDefaultInstance();
      } else {
        if (dataCase_ == 1) {
          return updateDataBuilder_.getMessage();
        }
        return com.textrcs.gmproto.client.UpdateConversationData.getDefaultInstance();
      }
    }
    /**
     * <code>.client.UpdateConversationData updateData = 1;</code>
     */
    public Builder setUpdateData(com.textrcs.gmproto.client.UpdateConversationData value) {
      if (updateDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        updateDataBuilder_.setMessage(value);
      }
      dataCase_ = 1;
      return this;
    }
    /**
     * <code>.client.UpdateConversationData updateData = 1;</code>
     */
    public Builder setUpdateData(
        com.textrcs.gmproto.client.UpdateConversationData.Builder builderForValue) {
      if (updateDataBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        updateDataBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 1;
      return this;
    }
    /**
     * <code>.client.UpdateConversationData updateData = 1;</code>
     */
    public Builder mergeUpdateData(com.textrcs.gmproto.client.UpdateConversationData value) {
      if (updateDataBuilder_ == null) {
        if (dataCase_ == 1 &&
            data_ != com.textrcs.gmproto.client.UpdateConversationData.getDefaultInstance()) {
          data_ = com.textrcs.gmproto.client.UpdateConversationData.newBuilder((com.textrcs.gmproto.client.UpdateConversationData) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 1) {
          updateDataBuilder_.mergeFrom(value);
        } else {
          updateDataBuilder_.setMessage(value);
        }
      }
      dataCase_ = 1;
      return this;
    }
    /**
     * <code>.client.UpdateConversationData updateData = 1;</code>
     */
    public Builder clearUpdateData() {
      if (updateDataBuilder_ == null) {
        if (dataCase_ == 1) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 1) {
          dataCase_ = 0;
          data_ = null;
        }
        updateDataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.client.UpdateConversationData updateData = 1;</code>
     */
    public com.textrcs.gmproto.client.UpdateConversationData.Builder getUpdateDataBuilder() {
      return getUpdateDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.client.UpdateConversationData updateData = 1;</code>
     */
    @java.lang.Override
    public com.textrcs.gmproto.client.UpdateConversationDataOrBuilder getUpdateDataOrBuilder() {
      if ((dataCase_ == 1) && (updateDataBuilder_ != null)) {
        return updateDataBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 1) {
          return (com.textrcs.gmproto.client.UpdateConversationData) data_;
        }
        return com.textrcs.gmproto.client.UpdateConversationData.getDefaultInstance();
      }
    }
    /**
     * <code>.client.UpdateConversationData updateData = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.textrcs.gmproto.client.UpdateConversationData, com.textrcs.gmproto.client.UpdateConversationData.Builder, com.textrcs.gmproto.client.UpdateConversationDataOrBuilder> 
        getUpdateDataFieldBuilder() {
      if (updateDataBuilder_ == null) {
        if (!(dataCase_ == 1)) {
          data_ = com.textrcs.gmproto.client.UpdateConversationData.getDefaultInstance();
        }
        updateDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.textrcs.gmproto.client.UpdateConversationData, com.textrcs.gmproto.client.UpdateConversationData.Builder, com.textrcs.gmproto.client.UpdateConversationDataOrBuilder>(
                (com.textrcs.gmproto.client.UpdateConversationData) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 1;
      onChanged();
      return updateDataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:client.UpdateConversationRequest)
  }

  // @@protoc_insertion_point(class_scope:client.UpdateConversationRequest)
  private static final com.textrcs.gmproto.client.UpdateConversationRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.textrcs.gmproto.client.UpdateConversationRequest();
  }

  public static com.textrcs.gmproto.client.UpdateConversationRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateConversationRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateConversationRequest>() {
    @java.lang.Override
    public UpdateConversationRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UpdateConversationRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateConversationRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.textrcs.gmproto.client.UpdateConversationRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

