// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ukey.proto

package com.textrcs.gmproto.ukey;

/**
 * <pre>
 * A convenience proto for encoding RSA public keys with small exponents
 * </pre>
 *
 * Protobuf type {@code ukey.SimpleRsaPublicKey}
 */
public final class SimpleRsaPublicKey extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ukey.SimpleRsaPublicKey)
    SimpleRsaPublicKeyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SimpleRsaPublicKey.newBuilder() to construct.
  private SimpleRsaPublicKey(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SimpleRsaPublicKey() {
    n_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SimpleRsaPublicKey();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.textrcs.gmproto.ukey.Ukey.internal_static_ukey_SimpleRsaPublicKey_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.textrcs.gmproto.ukey.Ukey.internal_static_ukey_SimpleRsaPublicKey_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.textrcs.gmproto.ukey.SimpleRsaPublicKey.class, com.textrcs.gmproto.ukey.SimpleRsaPublicKey.Builder.class);
  }

  public static final int N_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString n_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * Encoded in big-endian two's complement
   * </pre>
   *
   * <code>bytes n = 1;</code>
   * @return The n.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getN() {
    return n_;
  }

  public static final int E_FIELD_NUMBER = 2;
  private int e_ = 0;
  /**
   * <code>int32 e = 2;</code>
   * @return The e.
   */
  @java.lang.Override
  public int getE() {
    return e_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!n_.isEmpty()) {
      output.writeBytes(1, n_);
    }
    if (e_ != 0) {
      output.writeInt32(2, e_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!n_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, n_);
    }
    if (e_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, e_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.textrcs.gmproto.ukey.SimpleRsaPublicKey)) {
      return super.equals(obj);
    }
    com.textrcs.gmproto.ukey.SimpleRsaPublicKey other = (com.textrcs.gmproto.ukey.SimpleRsaPublicKey) obj;

    if (!getN()
        .equals(other.getN())) return false;
    if (getE()
        != other.getE()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + N_FIELD_NUMBER;
    hash = (53 * hash) + getN().hashCode();
    hash = (37 * hash) + E_FIELD_NUMBER;
    hash = (53 * hash) + getE();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.textrcs.gmproto.ukey.SimpleRsaPublicKey parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.ukey.SimpleRsaPublicKey parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.ukey.SimpleRsaPublicKey parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.ukey.SimpleRsaPublicKey parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.ukey.SimpleRsaPublicKey parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.ukey.SimpleRsaPublicKey parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.ukey.SimpleRsaPublicKey parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.ukey.SimpleRsaPublicKey parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.textrcs.gmproto.ukey.SimpleRsaPublicKey parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.ukey.SimpleRsaPublicKey parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.textrcs.gmproto.ukey.SimpleRsaPublicKey parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.ukey.SimpleRsaPublicKey parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.textrcs.gmproto.ukey.SimpleRsaPublicKey prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A convenience proto for encoding RSA public keys with small exponents
   * </pre>
   *
   * Protobuf type {@code ukey.SimpleRsaPublicKey}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ukey.SimpleRsaPublicKey)
      com.textrcs.gmproto.ukey.SimpleRsaPublicKeyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.textrcs.gmproto.ukey.Ukey.internal_static_ukey_SimpleRsaPublicKey_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.textrcs.gmproto.ukey.Ukey.internal_static_ukey_SimpleRsaPublicKey_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.textrcs.gmproto.ukey.SimpleRsaPublicKey.class, com.textrcs.gmproto.ukey.SimpleRsaPublicKey.Builder.class);
    }

    // Construct using com.textrcs.gmproto.ukey.SimpleRsaPublicKey.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      n_ = com.google.protobuf.ByteString.EMPTY;
      e_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.textrcs.gmproto.ukey.Ukey.internal_static_ukey_SimpleRsaPublicKey_descriptor;
    }

    @java.lang.Override
    public com.textrcs.gmproto.ukey.SimpleRsaPublicKey getDefaultInstanceForType() {
      return com.textrcs.gmproto.ukey.SimpleRsaPublicKey.getDefaultInstance();
    }

    @java.lang.Override
    public com.textrcs.gmproto.ukey.SimpleRsaPublicKey build() {
      com.textrcs.gmproto.ukey.SimpleRsaPublicKey result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.textrcs.gmproto.ukey.SimpleRsaPublicKey buildPartial() {
      com.textrcs.gmproto.ukey.SimpleRsaPublicKey result = new com.textrcs.gmproto.ukey.SimpleRsaPublicKey(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.textrcs.gmproto.ukey.SimpleRsaPublicKey result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.n_ = n_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.e_ = e_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.textrcs.gmproto.ukey.SimpleRsaPublicKey) {
        return mergeFrom((com.textrcs.gmproto.ukey.SimpleRsaPublicKey)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.textrcs.gmproto.ukey.SimpleRsaPublicKey other) {
      if (other == com.textrcs.gmproto.ukey.SimpleRsaPublicKey.getDefaultInstance()) return this;
      if (other.getN() != com.google.protobuf.ByteString.EMPTY) {
        setN(other.getN());
      }
      if (other.getE() != 0) {
        setE(other.getE());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              n_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              e_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString n_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Encoded in big-endian two's complement
     * </pre>
     *
     * <code>bytes n = 1;</code>
     * @return The n.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getN() {
      return n_;
    }
    /**
     * <pre>
     * Encoded in big-endian two's complement
     * </pre>
     *
     * <code>bytes n = 1;</code>
     * @param value The n to set.
     * @return This builder for chaining.
     */
    public Builder setN(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      n_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Encoded in big-endian two's complement
     * </pre>
     *
     * <code>bytes n = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearN() {
      bitField0_ = (bitField0_ & ~0x00000001);
      n_ = getDefaultInstance().getN();
      onChanged();
      return this;
    }

    private int e_ ;
    /**
     * <code>int32 e = 2;</code>
     * @return The e.
     */
    @java.lang.Override
    public int getE() {
      return e_;
    }
    /**
     * <code>int32 e = 2;</code>
     * @param value The e to set.
     * @return This builder for chaining.
     */
    public Builder setE(int value) {
      
      e_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 e = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearE() {
      bitField0_ = (bitField0_ & ~0x00000002);
      e_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ukey.SimpleRsaPublicKey)
  }

  // @@protoc_insertion_point(class_scope:ukey.SimpleRsaPublicKey)
  private static final com.textrcs.gmproto.ukey.SimpleRsaPublicKey DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.textrcs.gmproto.ukey.SimpleRsaPublicKey();
  }

  public static com.textrcs.gmproto.ukey.SimpleRsaPublicKey getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SimpleRsaPublicKey>
      PARSER = new com.google.protobuf.AbstractParser<SimpleRsaPublicKey>() {
    @java.lang.Override
    public SimpleRsaPublicKey parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SimpleRsaPublicKey> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SimpleRsaPublicKey> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.textrcs.gmproto.ukey.SimpleRsaPublicKey getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

