// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ukey.proto

package com.textrcs.gmproto.ukey;

public interface Ukey2MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ukey.Ukey2Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Identifies message type
   * </pre>
   *
   * <code>.ukey.Ukey2Message.Type message_type = 1;</code>
   * @return The enum numeric value on the wire for messageType.
   */
  int getMessageTypeValue();
  /**
   * <pre>
   * Identifies message type
   * </pre>
   *
   * <code>.ukey.Ukey2Message.Type message_type = 1;</code>
   * @return The messageType.
   */
  com.textrcs.gmproto.ukey.Ukey2Message.Type getMessageType();

  /**
   * <pre>
   * Actual message, to be parsed according to message_type
   * </pre>
   *
   * <code>bytes message_data = 2;</code>
   * @return The messageData.
   */
  com.google.protobuf.ByteString getMessageData();
}
