// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authentication.proto

package com.textrcs.gmproto.authentication;

public interface KeyDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:authentication.KeyData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.authentication.Device mobile = 1;</code>
   * @return Whether the mobile field is set.
   */
  boolean hasMobile();
  /**
   * <code>.authentication.Device mobile = 1;</code>
   * @return The mobile.
   */
  com.textrcs.gmproto.authentication.Device getMobile();
  /**
   * <code>.authentication.Device mobile = 1;</code>
   */
  com.textrcs.gmproto.authentication.DeviceOrBuilder getMobileOrBuilder();

  /**
   * <code>.authentication.ECDSAKeys ecdsaKeys = 6;</code>
   * @return Whether the ecdsaKeys field is set.
   */
  boolean hasEcdsaKeys();
  /**
   * <code>.authentication.ECDSAKeys ecdsaKeys = 6;</code>
   * @return The ecdsaKeys.
   */
  com.textrcs.gmproto.authentication.ECDSAKeys getEcdsaKeys();
  /**
   * <code>.authentication.ECDSAKeys ecdsaKeys = 6;</code>
   */
  com.textrcs.gmproto.authentication.ECDSAKeysOrBuilder getEcdsaKeysOrBuilder();

  /**
   * <code>.authentication.WebAuthKey webAuthKeyData = 2;</code>
   * @return Whether the webAuthKeyData field is set.
   */
  boolean hasWebAuthKeyData();
  /**
   * <code>.authentication.WebAuthKey webAuthKeyData = 2;</code>
   * @return The webAuthKeyData.
   */
  com.textrcs.gmproto.authentication.WebAuthKey getWebAuthKeyData();
  /**
   * <code>.authentication.WebAuthKey webAuthKeyData = 2;</code>
   */
  com.textrcs.gmproto.authentication.WebAuthKeyOrBuilder getWebAuthKeyDataOrBuilder();

  /**
   * <code>.authentication.Device browser = 3;</code>
   * @return Whether the browser field is set.
   */
  boolean hasBrowser();
  /**
   * <code>.authentication.Device browser = 3;</code>
   * @return The browser.
   */
  com.textrcs.gmproto.authentication.Device getBrowser();
  /**
   * <code>.authentication.Device browser = 3;</code>
   */
  com.textrcs.gmproto.authentication.DeviceOrBuilder getBrowserOrBuilder();
}
