// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authentication.proto

package com.textrcs.gmproto.authentication;

/**
 * Protobuf type {@code authentication.RefreshPhoneRelayResponse}
 */
public final class RefreshPhoneRelayResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:authentication.RefreshPhoneRelayResponse)
    RefreshPhoneRelayResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RefreshPhoneRelayResponse.newBuilder() to construct.
  private RefreshPhoneRelayResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RefreshPhoneRelayResponse() {
    pairKey_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RefreshPhoneRelayResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.textrcs.gmproto.authentication.Authentication.internal_static_authentication_RefreshPhoneRelayResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.textrcs.gmproto.authentication.Authentication.internal_static_authentication_RefreshPhoneRelayResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse.class, com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse.Builder.class);
  }

  public static final int COORDINATES_FIELD_NUMBER = 1;
  private com.textrcs.gmproto.authentication.CoordinateMessage coordinates_;
  /**
   * <code>.authentication.CoordinateMessage coordinates = 1;</code>
   * @return Whether the coordinates field is set.
   */
  @java.lang.Override
  public boolean hasCoordinates() {
    return coordinates_ != null;
  }
  /**
   * <code>.authentication.CoordinateMessage coordinates = 1;</code>
   * @return The coordinates.
   */
  @java.lang.Override
  public com.textrcs.gmproto.authentication.CoordinateMessage getCoordinates() {
    return coordinates_ == null ? com.textrcs.gmproto.authentication.CoordinateMessage.getDefaultInstance() : coordinates_;
  }
  /**
   * <code>.authentication.CoordinateMessage coordinates = 1;</code>
   */
  @java.lang.Override
  public com.textrcs.gmproto.authentication.CoordinateMessageOrBuilder getCoordinatesOrBuilder() {
    return coordinates_ == null ? com.textrcs.gmproto.authentication.CoordinateMessage.getDefaultInstance() : coordinates_;
  }

  public static final int PAIRKEY_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString pairKey_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes pairKey = 2;</code>
   * @return The pairKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPairKey() {
    return pairKey_;
  }

  public static final int VALIDFOR_FIELD_NUMBER = 3;
  private long validFor_ = 0L;
  /**
   * <code>int64 validFor = 3;</code>
   * @return The validFor.
   */
  @java.lang.Override
  public long getValidFor() {
    return validFor_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (coordinates_ != null) {
      output.writeMessage(1, getCoordinates());
    }
    if (!pairKey_.isEmpty()) {
      output.writeBytes(2, pairKey_);
    }
    if (validFor_ != 0L) {
      output.writeInt64(3, validFor_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (coordinates_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCoordinates());
    }
    if (!pairKey_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, pairKey_);
    }
    if (validFor_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, validFor_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse)) {
      return super.equals(obj);
    }
    com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse other = (com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse) obj;

    if (hasCoordinates() != other.hasCoordinates()) return false;
    if (hasCoordinates()) {
      if (!getCoordinates()
          .equals(other.getCoordinates())) return false;
    }
    if (!getPairKey()
        .equals(other.getPairKey())) return false;
    if (getValidFor()
        != other.getValidFor()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCoordinates()) {
      hash = (37 * hash) + COORDINATES_FIELD_NUMBER;
      hash = (53 * hash) + getCoordinates().hashCode();
    }
    hash = (37 * hash) + PAIRKEY_FIELD_NUMBER;
    hash = (53 * hash) + getPairKey().hashCode();
    hash = (37 * hash) + VALIDFOR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getValidFor());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code authentication.RefreshPhoneRelayResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:authentication.RefreshPhoneRelayResponse)
      com.textrcs.gmproto.authentication.RefreshPhoneRelayResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.textrcs.gmproto.authentication.Authentication.internal_static_authentication_RefreshPhoneRelayResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.textrcs.gmproto.authentication.Authentication.internal_static_authentication_RefreshPhoneRelayResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse.class, com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse.Builder.class);
    }

    // Construct using com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      coordinates_ = null;
      if (coordinatesBuilder_ != null) {
        coordinatesBuilder_.dispose();
        coordinatesBuilder_ = null;
      }
      pairKey_ = com.google.protobuf.ByteString.EMPTY;
      validFor_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.textrcs.gmproto.authentication.Authentication.internal_static_authentication_RefreshPhoneRelayResponse_descriptor;
    }

    @java.lang.Override
    public com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse getDefaultInstanceForType() {
      return com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse build() {
      com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse buildPartial() {
      com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse result = new com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.coordinates_ = coordinatesBuilder_ == null
            ? coordinates_
            : coordinatesBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.pairKey_ = pairKey_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.validFor_ = validFor_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse) {
        return mergeFrom((com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse other) {
      if (other == com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse.getDefaultInstance()) return this;
      if (other.hasCoordinates()) {
        mergeCoordinates(other.getCoordinates());
      }
      if (other.getPairKey() != com.google.protobuf.ByteString.EMPTY) {
        setPairKey(other.getPairKey());
      }
      if (other.getValidFor() != 0L) {
        setValidFor(other.getValidFor());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getCoordinatesFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              pairKey_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              validFor_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.textrcs.gmproto.authentication.CoordinateMessage coordinates_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.textrcs.gmproto.authentication.CoordinateMessage, com.textrcs.gmproto.authentication.CoordinateMessage.Builder, com.textrcs.gmproto.authentication.CoordinateMessageOrBuilder> coordinatesBuilder_;
    /**
     * <code>.authentication.CoordinateMessage coordinates = 1;</code>
     * @return Whether the coordinates field is set.
     */
    public boolean hasCoordinates() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.authentication.CoordinateMessage coordinates = 1;</code>
     * @return The coordinates.
     */
    public com.textrcs.gmproto.authentication.CoordinateMessage getCoordinates() {
      if (coordinatesBuilder_ == null) {
        return coordinates_ == null ? com.textrcs.gmproto.authentication.CoordinateMessage.getDefaultInstance() : coordinates_;
      } else {
        return coordinatesBuilder_.getMessage();
      }
    }
    /**
     * <code>.authentication.CoordinateMessage coordinates = 1;</code>
     */
    public Builder setCoordinates(com.textrcs.gmproto.authentication.CoordinateMessage value) {
      if (coordinatesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        coordinates_ = value;
      } else {
        coordinatesBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.authentication.CoordinateMessage coordinates = 1;</code>
     */
    public Builder setCoordinates(
        com.textrcs.gmproto.authentication.CoordinateMessage.Builder builderForValue) {
      if (coordinatesBuilder_ == null) {
        coordinates_ = builderForValue.build();
      } else {
        coordinatesBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.authentication.CoordinateMessage coordinates = 1;</code>
     */
    public Builder mergeCoordinates(com.textrcs.gmproto.authentication.CoordinateMessage value) {
      if (coordinatesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          coordinates_ != null &&
          coordinates_ != com.textrcs.gmproto.authentication.CoordinateMessage.getDefaultInstance()) {
          getCoordinatesBuilder().mergeFrom(value);
        } else {
          coordinates_ = value;
        }
      } else {
        coordinatesBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.authentication.CoordinateMessage coordinates = 1;</code>
     */
    public Builder clearCoordinates() {
      bitField0_ = (bitField0_ & ~0x00000001);
      coordinates_ = null;
      if (coordinatesBuilder_ != null) {
        coordinatesBuilder_.dispose();
        coordinatesBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.authentication.CoordinateMessage coordinates = 1;</code>
     */
    public com.textrcs.gmproto.authentication.CoordinateMessage.Builder getCoordinatesBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getCoordinatesFieldBuilder().getBuilder();
    }
    /**
     * <code>.authentication.CoordinateMessage coordinates = 1;</code>
     */
    public com.textrcs.gmproto.authentication.CoordinateMessageOrBuilder getCoordinatesOrBuilder() {
      if (coordinatesBuilder_ != null) {
        return coordinatesBuilder_.getMessageOrBuilder();
      } else {
        return coordinates_ == null ?
            com.textrcs.gmproto.authentication.CoordinateMessage.getDefaultInstance() : coordinates_;
      }
    }
    /**
     * <code>.authentication.CoordinateMessage coordinates = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.textrcs.gmproto.authentication.CoordinateMessage, com.textrcs.gmproto.authentication.CoordinateMessage.Builder, com.textrcs.gmproto.authentication.CoordinateMessageOrBuilder> 
        getCoordinatesFieldBuilder() {
      if (coordinatesBuilder_ == null) {
        coordinatesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.textrcs.gmproto.authentication.CoordinateMessage, com.textrcs.gmproto.authentication.CoordinateMessage.Builder, com.textrcs.gmproto.authentication.CoordinateMessageOrBuilder>(
                getCoordinates(),
                getParentForChildren(),
                isClean());
        coordinates_ = null;
      }
      return coordinatesBuilder_;
    }

    private com.google.protobuf.ByteString pairKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes pairKey = 2;</code>
     * @return The pairKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPairKey() {
      return pairKey_;
    }
    /**
     * <code>bytes pairKey = 2;</code>
     * @param value The pairKey to set.
     * @return This builder for chaining.
     */
    public Builder setPairKey(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      pairKey_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bytes pairKey = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPairKey() {
      bitField0_ = (bitField0_ & ~0x00000002);
      pairKey_ = getDefaultInstance().getPairKey();
      onChanged();
      return this;
    }

    private long validFor_ ;
    /**
     * <code>int64 validFor = 3;</code>
     * @return The validFor.
     */
    @java.lang.Override
    public long getValidFor() {
      return validFor_;
    }
    /**
     * <code>int64 validFor = 3;</code>
     * @param value The validFor to set.
     * @return This builder for chaining.
     */
    public Builder setValidFor(long value) {
      
      validFor_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 validFor = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearValidFor() {
      bitField0_ = (bitField0_ & ~0x00000004);
      validFor_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:authentication.RefreshPhoneRelayResponse)
  }

  // @@protoc_insertion_point(class_scope:authentication.RefreshPhoneRelayResponse)
  private static final com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse();
  }

  public static com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RefreshPhoneRelayResponse>
      PARSER = new com.google.protobuf.AbstractParser<RefreshPhoneRelayResponse>() {
    @java.lang.Override
    public RefreshPhoneRelayResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RefreshPhoneRelayResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RefreshPhoneRelayResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.textrcs.gmproto.authentication.RefreshPhoneRelayResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

