// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: events.proto

package com.textrcs.gmproto.events;

/**
 * Protobuf type {@code events.EncryptedData2Container}
 */
public final class EncryptedData2Container extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:events.EncryptedData2Container)
    EncryptedData2ContainerOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EncryptedData2Container.newBuilder() to construct.
  private EncryptedData2Container(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EncryptedData2Container() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EncryptedData2Container();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.textrcs.gmproto.events.Events.internal_static_events_EncryptedData2Container_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.textrcs.gmproto.events.Events.internal_static_events_EncryptedData2Container_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.textrcs.gmproto.events.EncryptedData2Container.class, com.textrcs.gmproto.events.EncryptedData2Container.Builder.class);
  }

  public static final int ACCOUNTCHANGE_FIELD_NUMBER = 2;
  private com.textrcs.gmproto.events.AccountChangeOrSomethingEvent accountChange_;
  /**
   * <code>.events.AccountChangeOrSomethingEvent accountChange = 2;</code>
   * @return Whether the accountChange field is set.
   */
  @java.lang.Override
  public boolean hasAccountChange() {
    return accountChange_ != null;
  }
  /**
   * <code>.events.AccountChangeOrSomethingEvent accountChange = 2;</code>
   * @return The accountChange.
   */
  @java.lang.Override
  public com.textrcs.gmproto.events.AccountChangeOrSomethingEvent getAccountChange() {
    return accountChange_ == null ? com.textrcs.gmproto.events.AccountChangeOrSomethingEvent.getDefaultInstance() : accountChange_;
  }
  /**
   * <code>.events.AccountChangeOrSomethingEvent accountChange = 2;</code>
   */
  @java.lang.Override
  public com.textrcs.gmproto.events.AccountChangeOrSomethingEventOrBuilder getAccountChangeOrBuilder() {
    return accountChange_ == null ? com.textrcs.gmproto.events.AccountChangeOrSomethingEvent.getDefaultInstance() : accountChange_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (accountChange_ != null) {
      output.writeMessage(2, getAccountChange());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (accountChange_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getAccountChange());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.textrcs.gmproto.events.EncryptedData2Container)) {
      return super.equals(obj);
    }
    com.textrcs.gmproto.events.EncryptedData2Container other = (com.textrcs.gmproto.events.EncryptedData2Container) obj;

    if (hasAccountChange() != other.hasAccountChange()) return false;
    if (hasAccountChange()) {
      if (!getAccountChange()
          .equals(other.getAccountChange())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAccountChange()) {
      hash = (37 * hash) + ACCOUNTCHANGE_FIELD_NUMBER;
      hash = (53 * hash) + getAccountChange().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.textrcs.gmproto.events.EncryptedData2Container parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.events.EncryptedData2Container parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.events.EncryptedData2Container parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.events.EncryptedData2Container parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.events.EncryptedData2Container parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.textrcs.gmproto.events.EncryptedData2Container parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.textrcs.gmproto.events.EncryptedData2Container parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.events.EncryptedData2Container parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.textrcs.gmproto.events.EncryptedData2Container parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.events.EncryptedData2Container parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.textrcs.gmproto.events.EncryptedData2Container parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.textrcs.gmproto.events.EncryptedData2Container parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.textrcs.gmproto.events.EncryptedData2Container prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code events.EncryptedData2Container}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:events.EncryptedData2Container)
      com.textrcs.gmproto.events.EncryptedData2ContainerOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.textrcs.gmproto.events.Events.internal_static_events_EncryptedData2Container_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.textrcs.gmproto.events.Events.internal_static_events_EncryptedData2Container_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.textrcs.gmproto.events.EncryptedData2Container.class, com.textrcs.gmproto.events.EncryptedData2Container.Builder.class);
    }

    // Construct using com.textrcs.gmproto.events.EncryptedData2Container.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      accountChange_ = null;
      if (accountChangeBuilder_ != null) {
        accountChangeBuilder_.dispose();
        accountChangeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.textrcs.gmproto.events.Events.internal_static_events_EncryptedData2Container_descriptor;
    }

    @java.lang.Override
    public com.textrcs.gmproto.events.EncryptedData2Container getDefaultInstanceForType() {
      return com.textrcs.gmproto.events.EncryptedData2Container.getDefaultInstance();
    }

    @java.lang.Override
    public com.textrcs.gmproto.events.EncryptedData2Container build() {
      com.textrcs.gmproto.events.EncryptedData2Container result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.textrcs.gmproto.events.EncryptedData2Container buildPartial() {
      com.textrcs.gmproto.events.EncryptedData2Container result = new com.textrcs.gmproto.events.EncryptedData2Container(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.textrcs.gmproto.events.EncryptedData2Container result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.accountChange_ = accountChangeBuilder_ == null
            ? accountChange_
            : accountChangeBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.textrcs.gmproto.events.EncryptedData2Container) {
        return mergeFrom((com.textrcs.gmproto.events.EncryptedData2Container)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.textrcs.gmproto.events.EncryptedData2Container other) {
      if (other == com.textrcs.gmproto.events.EncryptedData2Container.getDefaultInstance()) return this;
      if (other.hasAccountChange()) {
        mergeAccountChange(other.getAccountChange());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              input.readMessage(
                  getAccountChangeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.textrcs.gmproto.events.AccountChangeOrSomethingEvent accountChange_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.textrcs.gmproto.events.AccountChangeOrSomethingEvent, com.textrcs.gmproto.events.AccountChangeOrSomethingEvent.Builder, com.textrcs.gmproto.events.AccountChangeOrSomethingEventOrBuilder> accountChangeBuilder_;
    /**
     * <code>.events.AccountChangeOrSomethingEvent accountChange = 2;</code>
     * @return Whether the accountChange field is set.
     */
    public boolean hasAccountChange() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.events.AccountChangeOrSomethingEvent accountChange = 2;</code>
     * @return The accountChange.
     */
    public com.textrcs.gmproto.events.AccountChangeOrSomethingEvent getAccountChange() {
      if (accountChangeBuilder_ == null) {
        return accountChange_ == null ? com.textrcs.gmproto.events.AccountChangeOrSomethingEvent.getDefaultInstance() : accountChange_;
      } else {
        return accountChangeBuilder_.getMessage();
      }
    }
    /**
     * <code>.events.AccountChangeOrSomethingEvent accountChange = 2;</code>
     */
    public Builder setAccountChange(com.textrcs.gmproto.events.AccountChangeOrSomethingEvent value) {
      if (accountChangeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        accountChange_ = value;
      } else {
        accountChangeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.events.AccountChangeOrSomethingEvent accountChange = 2;</code>
     */
    public Builder setAccountChange(
        com.textrcs.gmproto.events.AccountChangeOrSomethingEvent.Builder builderForValue) {
      if (accountChangeBuilder_ == null) {
        accountChange_ = builderForValue.build();
      } else {
        accountChangeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.events.AccountChangeOrSomethingEvent accountChange = 2;</code>
     */
    public Builder mergeAccountChange(com.textrcs.gmproto.events.AccountChangeOrSomethingEvent value) {
      if (accountChangeBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          accountChange_ != null &&
          accountChange_ != com.textrcs.gmproto.events.AccountChangeOrSomethingEvent.getDefaultInstance()) {
          getAccountChangeBuilder().mergeFrom(value);
        } else {
          accountChange_ = value;
        }
      } else {
        accountChangeBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.events.AccountChangeOrSomethingEvent accountChange = 2;</code>
     */
    public Builder clearAccountChange() {
      bitField0_ = (bitField0_ & ~0x00000001);
      accountChange_ = null;
      if (accountChangeBuilder_ != null) {
        accountChangeBuilder_.dispose();
        accountChangeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.events.AccountChangeOrSomethingEvent accountChange = 2;</code>
     */
    public com.textrcs.gmproto.events.AccountChangeOrSomethingEvent.Builder getAccountChangeBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getAccountChangeFieldBuilder().getBuilder();
    }
    /**
     * <code>.events.AccountChangeOrSomethingEvent accountChange = 2;</code>
     */
    public com.textrcs.gmproto.events.AccountChangeOrSomethingEventOrBuilder getAccountChangeOrBuilder() {
      if (accountChangeBuilder_ != null) {
        return accountChangeBuilder_.getMessageOrBuilder();
      } else {
        return accountChange_ == null ?
            com.textrcs.gmproto.events.AccountChangeOrSomethingEvent.getDefaultInstance() : accountChange_;
      }
    }
    /**
     * <code>.events.AccountChangeOrSomethingEvent accountChange = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.textrcs.gmproto.events.AccountChangeOrSomethingEvent, com.textrcs.gmproto.events.AccountChangeOrSomethingEvent.Builder, com.textrcs.gmproto.events.AccountChangeOrSomethingEventOrBuilder> 
        getAccountChangeFieldBuilder() {
      if (accountChangeBuilder_ == null) {
        accountChangeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.textrcs.gmproto.events.AccountChangeOrSomethingEvent, com.textrcs.gmproto.events.AccountChangeOrSomethingEvent.Builder, com.textrcs.gmproto.events.AccountChangeOrSomethingEventOrBuilder>(
                getAccountChange(),
                getParentForChildren(),
                isClean());
        accountChange_ = null;
      }
      return accountChangeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:events.EncryptedData2Container)
  }

  // @@protoc_insertion_point(class_scope:events.EncryptedData2Container)
  private static final com.textrcs.gmproto.events.EncryptedData2Container DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.textrcs.gmproto.events.EncryptedData2Container();
  }

  public static com.textrcs.gmproto.events.EncryptedData2Container getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EncryptedData2Container>
      PARSER = new com.google.protobuf.AbstractParser<EncryptedData2Container>() {
    @java.lang.Override
    public EncryptedData2Container parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EncryptedData2Container> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EncryptedData2Container> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.textrcs.gmproto.events.EncryptedData2Container getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

