// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: events.proto

package com.textrcs.gmproto.events;

public interface TypingEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:events.TypingEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.events.TypingData data = 2;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.events.TypingData data = 2;</code>
   * @return The data.
   */
  com.textrcs.gmproto.events.TypingData getData();
  /**
   * <code>.events.TypingData data = 2;</code>
   */
  com.textrcs.gmproto.events.TypingDataOrBuilder getDataOrBuilder();
}
